Repository valora-inc/wallet, pull requests merged in 2021-05, with the labels that each got.

#298 chore: update and rename config.yaml to config.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: automerge, documentation

#289 Fix migration error causing to lose the existing redux state
  packages/mobile/__mocks__/src/utils/Logger.ts
  packages/mobile/jest_setup.ts
  packages/mobile/src/app/Debug.test.tsx
  packages/mobile/src/redux/createMigrate.test.ts
  packages/mobile/src/redux/createMigrate.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/store.ts
  packages/react-components/services/ReactNativeLogger.ts
Labels: automerge

#304 Bump `resource_class` to `large` to fix `general-tests` randomly failing with exit code 137
  .circleci/config.yml
Labels: automerge

#301 [Wallet] Update @celo/client to v1.3.0-stable
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#299 Tomm/flipper upate
  packages/mobile/Gemfile.lock
  packages/mobile/README.md
  packages/mobile/e2e/README.md
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
Labels: Component: Tests, tech-debt

#314 [Wallet] Fix incorrect analytics event sent when choosing restore account
  packages/mobile/src/analytics/Events.test.tsx
  packages/mobile/src/analytics/Events.tsx
Labels: automerge

#309 Upgrade react-native-safe-area-context to 3.2.0
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/react-components/package.json
  yarn.lock
Labels: automerge

#291 Update SDK version to 1.2 - Return user's pepper in dappkit
  packages/komencikit/package.json
  packages/mobile/package.json
  packages/mobile/scripts/run_app.sh
  packages/mobile/src/dappkit/dappkit.ts
  packages/mobile/src/identity/revoke.ts
  packages/mobile/src/web3/dataEncryptionKey.ts
  yarn.lock
Labels: automerge

#164 Fire BigQuery events on CICO webhooks
  packages/cloud-functions/package.json
  packages/cloud-functions/src/bigQuery.ts
  packages/cloud-functions/src/cico/Provider.ts
  packages/cloud-functions/src/cico/Simplex.ts
  packages/cloud-functions/src/cico/moonpayWebhook.ts
  packages/cloud-functions/src/cico/rampWebhook.ts
  packages/cloud-functions/src/config.ts
  yarn.lock
Labels: automerge

#316 Tomm/doc update
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/2-feature-request.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: automerge, documentation, wallet

#297 Add Transak webhook
  packages/cloud-functions/src/cico/transakWebhook.ts
  packages/cloud-functions/src/index.ts
Labels: automerge

#154 WalletConnect
  .circleci/config.yml
  packages/mobile/.env.mainnet
  packages/mobile/e2e/.gitignore
  packages/mobile/e2e/README.md
  packages/mobile/e2e/src/usecases/WalletConnect.js
  packages/mobile/ios/Podfile.lock
  packages/mobile/jest.config.js
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/index.ts
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/en-US/walletConnect.json
  packages/mobile/package.json
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/app/reducers.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/i18n.ts
  packages/mobile/src/missingGlobals.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/qrcode/QRScanner.tsx
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/redux/reducers.ts
  packages/mobile/src/redux/sagas.ts
  packages/mobile/src/walletConnect/actions.ts
  packages/mobile/src/walletConnect/constants.ts
  packages/mobile/src/walletConnect/reducer.ts
  packages/mobile/src/walletConnect/saga.ts
  packages/mobile/src/walletConnect/screens/ActionRequest.tsx
  packages/mobile/src/walletConnect/screens/SessionRequest.tsx
  packages/mobile/src/walletConnect/screens/Sessions.tsx
  packages/mobile/src/walletConnect/selectors.ts
  packages/mobile/src/walletConnect/walletConnect.ts
  packages/mobile/test/schemas.ts
  yarn.lock
Labels: automerge

#326 Initialize sentry earlier
  packages/mobile/index.js
  packages/mobile/src/redux/store.ts
  packages/mobile/src/sentry/Sentry.ts
Labels: automerge

#331 [Wallet] Trigger app tracking authorization popup on iOS
  crowdin.yml
  packages/mobile/.gitignore
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo/Base.lproj/InfoPlist.strings
  packages/mobile/ios/celo/Info.plist
  packages/mobile/package.json
  packages/mobile/scripts/sync_ios_info_plist_strings.sh
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/analytics/ValoraAnalytics.ts
  yarn.lock
Labels: automerge

#323 Move provider logic server-side
  packages/cloud-functions/package.json
  packages/cloud-functions/src/cico/Providers.ts
  packages/cloud-functions/src/cico/Simplex.ts
  packages/cloud-functions/src/cico/composeCicoProviderUrl.ts
  packages/cloud-functions/src/cico/composeProviderUrl.ts
  packages/cloud-functions/src/cico/fetchProviders.ts
  packages/cloud-functions/src/cico/moonpayWebhook.test.ts
  packages/cloud-functions/src/cico/moonpayWebhook.ts
  packages/cloud-functions/src/cico/providerAvailability.ts
  packages/cloud-functions/src/cico/rampWebhook.test.ts
  packages/cloud-functions/src/cico/rampWebhook.ts
  packages/cloud-functions/src/cico/transakWebhook.ts
  packages/cloud-functions/src/cico/utils.ts
  packages/cloud-functions/src/config.ts
  packages/cloud-functions/src/index.ts
  packages/mobile/locales/en-US/global.json
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/fiatExchanges/CashInSuccess.test.tsx
  packages/mobile/src/fiatExchanges/MoonPayScreen.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/RampScreen.tsx
  packages/mobile/src/fiatExchanges/SimplexScreen.tsx
  packages/mobile/src/fiatExchanges/TransakScreen.tsx
  packages/mobile/src/fiatExchanges/XanpoolScreen.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/ProviderOptionsScreen.test.tsx.snap
  packages/mobile/src/fiatExchanges/actions.ts
  packages/mobile/src/fiatExchanges/reducer.test.ts
  packages/mobile/src/fiatExchanges/reducer.ts
  packages/mobile/src/fiatExchanges/saga.ts
  packages/mobile/src/fiatExchanges/utils.tsx
  packages/mobile/src/firebase/db-rules.json
  packages/mobile/src/flags.ts
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/utils/fetchWithTimeout.ts
  packages/mobile/test/schemas.ts
  packages/moonpay-auth/README.md
Labels: automerge

#351 Don't show invites until they can be reclaimed
  packages/mobile/src/config.ts
  packages/mobile/src/escrow/EscrowedPaymentListScreen.tsx
  packages/mobile/src/escrow/__mocks__.ts
  packages/mobile/src/escrow/reducer.ts
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/selectors.ts
Labels: automerge

#354 Use account address when giving CIP8 profile access
  packages/mobile/src/account/profileInfo.test.ts
  packages/mobile/src/account/profileInfo.ts
  packages/mobile/src/send/saga.ts
  packages/mobile/src/web3/dataEncryptionKey.ts
Labels: automerge

#352 P1 fixes for 1.14 release
  packages/mobile/e2e/src/usecases/HandleDeepLinkDappkit.js
  packages/mobile/src/recipients/RecipientItem.tsx
  packages/mobile/src/recipients/__snapshots__/RecipientItem.test.tsx.snap
  packages/mobile/src/redux/sagas.ts
  packages/mobile/src/send/__snapshots__/Send.test.tsx.snap
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/saga.ts
  packages/mobile/src/web3/dataEncryptionKey.ts
Labels: automerge

#335 Download profile info for each address once
  packages/mobile/src/account/profileInfo.ts
  packages/mobile/src/import/saga.ts
  packages/mobile/src/recipients/recipient.test.ts
  packages/mobile/src/recipients/recipient.ts
  packages/mobile/src/transactions/saga.ts
Labels: automerge

#367 Fix error running iOS e2e test locally
  packages/mobile/src/analytics/ValoraAnalytics.ts
Labels: automerge

#372 [Wallet] Fix `getAttestationCodeForSecurityCode` not logging error details
  packages/mobile/src/identity/securityCode.test.ts
  packages/mobile/src/identity/securityCode.ts
Labels: automerge

#382 Minor mobile readme updates
  packages/mobile/README.md
Labels: automerge

#378 Refactor the UI of the verification flow
  packages/mobile/src/components/CodeInput.test.tsx
  packages/mobile/src/components/CodeInput.tsx
  packages/mobile/src/components/__snapshots__/CodeInput.test.tsx.snap
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/import/ImportWallet.tsx
  packages/mobile/src/verify/VerificationCodeInput.test.tsx
  packages/mobile/src/verify/VerificationCodeInput.tsx
  packages/mobile/src/verify/VerificationInputScreen.test.tsx
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationCodeInput.test.tsx.snap
  packages/mobile/src/verify/utils.ts
  packages/mobile/test/schemas.ts
Labels: Component: Verification, automerge

#388 Restart verification if phone number changes
  packages/mobile/src/verify/VerificationEducationScreen.tsx
Labels: automerge

#383 Add migration to fix user verification state
  packages/mobile/src/app/actions.ts
  packages/mobile/src/app/reducers.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/app/verificationMigration.test.ts
  packages/mobile/src/app/verificationMigration.ts
  packages/mobile/src/web3/reducer.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#391 Prevent repeated code from being pasted in Android
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/smsRetrieval.ts
  packages/mobile/src/identity/verification.ts
Labels: Component: Verification, automerge

#397 Fix cash-out limit balance calculation with non-USD currencies
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.test.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap
Labels: automerge

#368 Modify notification service to support cEUR
  packages/notification-service/package.json
  packages/notification-service/src/exchange/exchangeQuery.ts
  yarn.lock
Labels: automerge

#409 Add section about Branding to README
  packages/mobile/README.md
Labels: automerge

#389 [WalletConnect] implement eth_signTypedData
  packages/mobile/src/walletConnect/saga.ts
Labels: automerge

#408 Update text of RaiseLimitScreen
  packages/mobile/src/account/RaiseLimitScreen.tsx
  packages/mobile/src/account/__snapshots__/RaiseLimitScreen.test.tsx.snap
  packages/mobile/src/firebase/firebase.ts
Labels: automerge

#410 Display contact phone numbers in the same format they are saved in
  packages/mobile/src/recipients/recipient.test.ts
  packages/mobile/src/recipients/recipient.ts
Labels: automerge

#418 Update resolutions to fix vulnerabilities
  package.json
  yarn.lock
Labels: automerge

#377 Merge main into "Verification Refactoring - Part #2"
  packages/mobile/docs/verification_state_machine.plantuml
  packages/mobile/docs/verification_state_machine.png
  packages/mobile/src/account/Settings.test.tsx
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/app/saga.test.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/app/selectors.test.ts
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/app/verificationMigration.test.ts
  packages/mobile/src/app/verificationMigration.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/feelessVerificationErrors.ts
  packages/mobile/src/identity/privateHashing.test.ts
  packages/mobile/src/identity/privateHashing.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/revoke.ts
  packages/mobile/src/identity/saga.ts
  packages/mobile/src/identity/smsRetrieval.ts
  packages/mobile/src/identity/types.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/reducers.ts
  packages/mobile/src/send/Send.test.tsx
  packages/mobile/src/verify/VerificationCodeInput.test.tsx
  packages/mobile/src/verify/VerificationCodeInput.tsx
  packages/mobile/src/verify/VerificationEducationScreen.test.tsx
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/VerificationFailedModal.tsx
  packages/mobile/src/verify/VerificationInputScreen.test.tsx
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.test.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/mobile/src/verify/komenci.test.ts
  packages/mobile/src/verify/komenci.ts
  packages/mobile/src/verify/module.ts
  packages/mobile/src/verify/requestAttestations.test.ts
  packages/mobile/src/verify/requestAttestations.ts
  packages/mobile/src/verify/revealAttestations.test.ts
  packages/mobile/src/verify/revealAttestations.ts
  packages/mobile/src/verify/saga.test.ts
  packages/mobile/src/verify/saga.ts
  packages/mobile/test/schemas.ts
  packages/mobile/test/values.ts
Labels: Component: Verification, automerge

#417 Fire analytics event when push notification is opened
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/firebase/notifications.test.ts
  packages/mobile/src/firebase/notifications.ts
  packages/mobile/src/notifications/types.ts
Labels: automerge

#411 Turn Send screen into a functional component
  packages/mobile/branding/celo/src/brandingConfig.ts
  packages/mobile/branding/celo/src/icons/Logo.tsx
  packages/mobile/locales/en-US/inviteFlow11.json
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/src/components/header/CustomHeader.tsx
  packages/mobile/src/icons/Invite.tsx
  packages/mobile/src/navigator/Headers.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/recipients/RecipientItem.test.tsx
  packages/mobile/src/recipients/RecipientItem.tsx
  packages/mobile/src/recipients/__snapshots__/RecipientItem.test.tsx.snap
  packages/mobile/src/recipients/recipient.ts
  packages/mobile/src/send/GetRewardPill.tsx
  packages/mobile/src/send/InviteRewardsBanner.tsx
  packages/mobile/src/send/Send.test.tsx
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/send/SendCallToAction.tsx
  packages/mobile/src/send/SendHeader.tsx
  packages/mobile/src/send/SendSearchInput.tsx
  packages/mobile/src/send/__snapshots__/Send.test.tsx.snap
  packages/mobile/src/send/__snapshots__/SendCallToAction.test.tsx.snap
  packages/mobile/src/send/actions.ts
  packages/mobile/src/send/utils.ts
Labels: automerge

#423 Exchange rate cloud function
  packages/cloud-functions/firebase-env-config.sh
  packages/cloud-functions/package.json
  packages/cloud-functions/src/config.ts
  packages/cloud-functions/src/contractKit.ts
  packages/cloud-functions/src/exchangeRate/index.ts
  packages/cloud-functions/src/exchangeRate/test.ts
  packages/cloud-functions/src/firebase.ts
  packages/cloud-functions/src/index.ts
  packages/cloud-functions/src/metrics.ts
  packages/notification-service/src/config.ts
  packages/notification-service/src/firebase.ts
  packages/notification-service/src/index.ts
  packages/notification-service/src/metrics.ts
  packages/notification-service/src/polling.ts
Labels: automerge
