Repository valora-inc/wallet, pull requests merged in 2021-06, with the labels that each got.

#431 Add migration to clean up old verification state
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/store.test.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#374 Percentage based Rewards Screen redesign
  packages/mobile/branding/celo/src/brandingConfig.ts
  packages/mobile/branding/celo/src/images/earn1.png
  packages/mobile/branding/celo/src/images/earn2.png
  packages/mobile/branding/celo/src/images/earn3.png
  packages/mobile/branding/celo/src/images/earnMain.png
  packages/mobile/locales/en-US/consumerIncentives.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/src/account/actions.ts
  packages/mobile/src/account/reducer.ts
  packages/mobile/src/app/actions.ts
  packages/mobile/src/app/reducers.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.test.tsx
  packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.tsx
  packages/mobile/src/consumerIncentives/__snapshots__/ConsumerIncentivesHomeScreen.test.tsx.snap
  packages/mobile/src/consumerIncentives/contentFetcher.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/icons/Rings.tsx
  packages/mobile/src/images/Images.ts
  packages/mobile/src/navigator/RewardsPill.test.tsx
  packages/mobile/src/navigator/RewardsPill.tsx
  packages/mobile/src/navigator/__snapshots__/RewardsPill.test.tsx.snap
  packages/mobile/src/transactions/TransferConfirmationCard.tsx
  packages/mobile/src/web3/selectors.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#358 Switch location detection from phone country code to IP address
  packages/cloud-functions/.env.alfajores.enc
  packages/cloud-functions/.env.mainnet.enc
  packages/cloud-functions/firebase-env-config.sh
  packages/cloud-functions/src/cico/fetchProviders.ts
  packages/cloud-functions/src/cico/fetchUserLocationData.ts
  packages/cloud-functions/src/cico/providerAvailability.ts
  packages/cloud-functions/src/config.ts
  packages/cloud-functions/src/index.ts
  packages/mobile/__mocks__/secrets.json
  packages/mobile/secrets.json.enc
  packages/mobile/src/config.ts
  packages/mobile/src/exchange/ExchangeHomeScreen.test.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/utils.tsx
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/home/selectors.test.ts
  packages/mobile/src/home/selectors.ts
  packages/mobile/src/networkInfo/actions.ts
  packages/mobile/src/networkInfo/reducer.ts
  packages/mobile/src/networkInfo/saga.ts
  packages/mobile/src/networkInfo/selectors.ts
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/src/utils/countryFeatures.test.ts
  packages/mobile/src/utils/countryFeatures.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#419 Add eslint to mobile and port over tslint configuration
  packages/eslint-config-typescript/README.md
  packages/eslint-config-typescript/index.js
  packages/eslint-config-typescript/package.json
  packages/mobile/.eslintrc.js
  packages/mobile/locales/en-US/index.ts
  packages/mobile/locales/es-419/index.ts
  packages/mobile/locales/pt-BR/index.ts
  packages/mobile/package.json
  packages/mobile/src/account/Profile.tsx
  packages/mobile/src/account/StoreWipeRecoveryScreen.tsx
  packages/mobile/src/backup/BackupPhraseContainer.tsx
  packages/mobile/src/components/FeeIcon.tsx
  packages/mobile/src/config.ts
  packages/mobile/src/fiatExchanges/BidaliScreen.test.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/ReviewFees.tsx
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/geth/saga.test.ts
  packages/mobile/src/geth/saga.ts
  packages/mobile/src/i18n.ts
  packages/mobile/src/identity/feelessVerificationErrors.ts
  packages/mobile/src/import/ImportWallet.tsx
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/localCurrency/SelectLocalCurrency.tsx
  packages/mobile/src/missingGlobals.ts
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/qrcode/QRScanner.tsx
  packages/mobile/src/redux/store.ts
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/ValidateRecipientAccount.tsx
  packages/mobile/src/send/utils.test.ts
  packages/mobile/src/transactions/send.ts
  packages/mobile/src/utils/LogUploader.ts
  packages/mobile/src/utils/countryFeatures.ts
  packages/mobile/src/utils/permissions.d.ts
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/mobile/src/walletConnect/screens/Sessions.tsx
  packages/mobile/src/web3/saga.ts
  packages/mobile/tslint.json
  yarn.lock
Labels: automerge

#384 Add Fees for CICO Providers
  packages/cloud-functions/.env.alfajores.enc
  packages/cloud-functions/.env.mainnet.enc
  packages/cloud-functions/codegen.yml
  packages/cloud-functions/firebase-env-config.sh
  packages/cloud-functions/jest.config.js
  packages/cloud-functions/jest_setup.ts
  packages/cloud-functions/package.json
  packages/cloud-functions/src/cico/Moonpay.test.ts
  packages/cloud-functions/src/cico/Moonpay.ts
  packages/cloud-functions/src/cico/Simplex.ts
  packages/cloud-functions/src/cico/Transak.test.ts
  packages/cloud-functions/src/cico/Transak.ts
  packages/cloud-functions/src/cico/Xanpool.test.ts
  packages/cloud-functions/src/cico/Xanpool.ts
  packages/cloud-functions/src/cico/composeCicoProviderUrl.ts
  packages/cloud-functions/src/cico/composeProviderUrl.ts
  packages/cloud-functions/src/cico/fetchProviders.ts
  packages/cloud-functions/src/cico/fetchUserLocationData.ts
  packages/cloud-functions/src/cico/providerAvailability.ts
  packages/cloud-functions/src/cico/utils.ts
  packages/cloud-functions/src/config.ts
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/ProviderOptionsScreen.test.tsx.snap
  packages/mobile/src/fiatExchanges/utils.tsx
  packages/mobile/src/networkInfo/saga.ts
  packages/mobile/src/utils/fetchWithTimeout.ts
  packages/moonpay-auth/package.json
Labels: automerge

#416 Focus number input when country changes on phone verification
  packages/react-components/components/PhoneNumberInput.tsx
  packages/react-components/components/TextInput.tsx
  packages/react-components/components/ValidatedTextInput.tsx
Labels: automerge

#438 Fixed the blockscout query parameter type
  packages/blockchain-api/src/blockscout.ts
Labels: automerge

#432 Various verification fixes
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/src/identity/smsRetrieval.ts
  packages/mobile/src/verify/komenci.ts
  packages/mobile/src/verify/module.ts
  packages/mobile/src/verify/requestAttestations.ts
  packages/mobile/src/verify/saga.ts
  packages/mobile/src/verify/sagas/resetKomenciSessionSaga.ts
Labels: automerge

#435 Convert package/react-components from tslint to eslint
  packages/react-components/.eslintrc.js
  packages/react-components/components/KeyboardSpacer.tsx
  packages/react-components/components/PhoneNumberInput.tsx
  packages/react-components/components/SmartTopAlert.tsx
  packages/react-components/package.json
  packages/react-components/services/ReactNativeLogger.ts
  packages/react-components/tslint.json
  yarn.lock
Labels: automerge

#437 [Wallet] Merge 1.14.3 release
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/android/sentry.properties.enc
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/ios/celo/Base.lproj/InfoPlist.strings
  packages/mobile/ios/celo/Info.plist
  packages/mobile/ios/sentry.properties.enc
  packages/mobile/locales/es-419/index.ts
  packages/mobile/locales/pt-BR/index.ts
  packages/mobile/package.json
Labels: automerge

#436 Add linting package to `cloud-functions` directory
  .github/CODEOWNERS
  packages/cloud-functions/.eslintrc.js
  packages/cloud-functions/package.json
  packages/cloud-functions/src/cico/transakWebhook.ts
  packages/cloud-functions/src/exchangeRate/index.ts
  packages/cloud-functions/src/exchangeRate/test.ts
  packages/cloud-functions/tsconfig.json
  packages/cloud-functions/tslint.json
  packages/eslint-config-typescript/index.js
  packages/mobile/tsconfig.json
Labels: automerge

#442 [WalletConnect] implement personal_decrypt
  packages/mobile/src/walletConnect/saga.ts
  packages/mobile/src/walletConnect/screens/ActionRequest.tsx
Labels: automerge

#221 Change PIN feature
  packages/mobile/__mocks__/src/pincode/authentication.ts
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/package.json
  packages/mobile/src/account/Settings.test.tsx
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/backup/utils.ts
  packages/mobile/src/geth/GethNativeBridgeWallet.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/pincode/Pincode.tsx
  packages/mobile/src/pincode/PincodeSet.test.tsx
  packages/mobile/src/pincode/PincodeSet.tsx
  packages/mobile/src/pincode/authentication.ts
  packages/mobile/src/web3/contracts.ts
  yarn.lock
Labels: automerge

#454 Don't start verification saga unless user starts verification
  packages/mobile/src/verify/saga.ts
Labels: automerge

#455 Patch vulnerability in `css-what`
  package.json
  yarn.lock
Labels: automerge

#430 Move payment request notifications to Cloud Function
  crowdin.yml
  packages/cloud-functions/.firebaserc
  packages/cloud-functions/.gitignore
  packages/cloud-functions/firebase.json
  packages/cloud-functions/jest_setup.ts
  packages/cloud-functions/locales/en.json
  packages/cloud-functions/locales/es.json
  packages/cloud-functions/locales/pt.json
  packages/cloud-functions/package.json
  packages/cloud-functions/src/config.ts
  packages/cloud-functions/src/exchangeRate/index.ts
  packages/cloud-functions/src/firebase.ts
  packages/cloud-functions/src/index.ts
  packages/cloud-functions/src/metrics.ts
  packages/cloud-functions/src/notifications/index.ts
  packages/cloud-functions/src/notifications/types.ts
  packages/cloud-functions/src/paymentRequests/index.ts
  packages/cloud-functions/src/paymentRequests/test.ts
  packages/cloud-functions/tsconfig.json
  packages/notification-service/src/firebase.ts
  packages/notification-service/src/handlers.ts
  packages/notification-service/src/metrics.ts
  packages/notification-service/src/polling.ts
  yarn.lock
Labels: automerge

#463 Fix miscount in attestation rerequest banner
  packages/mobile/src/verify/revealAttestations.ts
  packages/mobile/src/verify/saga.ts
Labels: TestQuality, automerge, requirement

#434 Account Number redesign
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/src/components/AccountNumber.test.tsx
  packages/mobile/src/components/AccountNumber.tsx
  packages/mobile/src/components/__snapshots__/AccountNumber.test.tsx.snap
  packages/mobile/src/navigator/DrawerNavigator.tsx
  packages/mobile/src/send/__snapshots__/ValidateRecipientAccount.test.tsx.snap
  packages/mobile/src/transactions/UserSection.tsx
Labels: automerge

#456 Copy the start of the indexer code into a separate package.
  packages/indexer/.gitignore
  packages/indexer/README.md
  packages/indexer/__mocks__/@celo/contractkit.ts
  packages/indexer/app.alfajores.yaml
  packages/indexer/app.mainnet.yaml
  packages/indexer/cloudbuild/cloudbuild.yaml
  packages/indexer/config/config.alfajores.env.enc
  packages/indexer/config/config.local.env
  packages/indexer/config/config.mainnet.env.enc
  packages/indexer/config/config.test.env
  packages/indexer/deploy.sh
  packages/indexer/index.d.ts
  packages/indexer/jest.config.js
  packages/indexer/jest.setup.ts
  packages/indexer/package.json
  packages/indexer/src/config.ts
  packages/indexer/src/database/db.ts
  packages/indexer/src/index.ts
  packages/indexer/src/indexer/accounts.ts
  packages/indexer/src/indexer/attestations.ts
  packages/indexer/src/indexer/blocks.ts
  packages/indexer/src/indexer/index.ts
  packages/indexer/src/indexer/invites.ts
  packages/indexer/src/indexer/transfers.ts
  packages/indexer/src/migrations/20210515032351_CreateWalletAddress.ts
  packages/indexer/src/migrations/20210515032409_CreateAttestationComplete.ts
  packages/indexer/src/migrations/20210515032417_CreateTransfers.ts
  packages/indexer/src/migrations/20210515033428_CreateLastBlocks.ts
  packages/indexer/src/migrations/20210515061128_CreateEscrowWithdrawal.ts
  packages/indexer/src/migrations/20210530051931_CreateIndexes.ts
  packages/indexer/src/polling.ts
  packages/indexer/src/util/testing.ts
  packages/indexer/src/util/utils.ts
  packages/indexer/test/indexer.test.ts
  packages/indexer/tsconfig.json
  packages/indexer/tslint.json
  packages/indexer/yarn.lock
  yarn.lock
Labels: automerge

#469 Vulnerability fix: force resolution of normalize-url 6.0.1
  package.json
  yarn.lock
Labels: automerge

#457 Tomm/detox test match
  .circleci/config.yml
  packages/mobile/e2e/README.md
  packages/mobile/scripts/run_e2e.sh
Labels: Component: Tests, automerge, wallet

#470 indexer: tslint -> eslint
  packages/indexer/.eslintrc.js
  packages/indexer/.gitignore
  packages/indexer/package.json
  packages/indexer/src/indexer/index.ts
  packages/indexer/tsconfig.eslint.json
  packages/indexer/tslint.json
  yarn.lock
Labels: automerge

#476 Move eslint-config-typescript to an @valora scope to facilitate publishing
  packages/cloud-functions/.eslintrc.js
  packages/cloud-functions/package.json
  packages/eslint-config-typescript/README.md
  packages/eslint-config-typescript/package.json
  packages/indexer/.eslintrc.js
  packages/indexer/package.json
  packages/mobile/.eslintrc.js
  packages/mobile/package.json
  packages/react-components/.eslintrc.js
  packages/react-components/package.json
Labels: automerge

#496 fix(indexer): make event insert and block increment atomic
  packages/indexer/src/database/db.ts
  packages/indexer/src/indexer/blocks.ts
  packages/indexer/src/indexer/index.ts
  packages/indexer/test/indexer.test.ts
Labels: automerge

#477 Upgrade to node 12
  .circleci/config.yml
  .github/workflows/checks.yml
  SETUP.md
  packages/blockchain-api/test/blockscout.test.ts
  packages/cloud-functions/package.json
  packages/dev-utils/package.json
  packages/indexer/package.json
  packages/komencikit/package.json
  packages/moonpay-auth/package.json
  packages/notification-service/package.json
Labels: automerge

#495 [Wallet] Update @celo/client to v1.3.2-stable
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#259 Support stable tokens in blockchain-api
  packages/blockchain-api/package.json
  packages/blockchain-api/src/blockscout.ts
  packages/blockchain-api/src/currencyConversion/CurrencyConversionAPI.test.ts
  packages/blockchain-api/src/currencyConversion/CurrencyConversionAPI.ts
  packages/blockchain-api/src/currencyConversion/consts.ts
  packages/blockchain-api/src/events/ExchangeCeloToToken.ts
  packages/blockchain-api/src/events/ExchangeTokenToCelo.ts
  packages/blockchain-api/src/helpers/EventBuilder.ts
  packages/blockchain-api/src/schema.ts
  packages/blockchain-api/src/transaction/TransactionType.ts
  packages/blockchain-api/test/any.test.ts
  packages/blockchain-api/yarn.lock
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#498 Make timestamps strictly increasing in blockscout mock data
  packages/blockchain-api/test/blockscout.test.ts
  packages/blockchain-api/test/mockTokenTxs.ts
Labels: automerge

#482 Update account number design in Exchanges screen
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/src/fiatExchanges/ExternalExchanges.tsx
Labels: automerge

#452 Show exact balance user needs in error banner
  packages/mobile/locales/en-US/global.json
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/src/send/SendAmount.tsx
Labels: automerge

#464 Show warning about sending a test transaction when sending to new addresses
  packages/mobile/e2e/src/usecases/Send.js
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/recipients/RecipientPicker.tsx
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/send/SendToAddressWarning.tsx
  packages/mobile/src/send/__snapshots__/Send.test.tsx.snap
  packages/mobile/src/send/actions.ts
  packages/mobile/src/send/reducers.ts
  packages/mobile/src/send/utils.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#499 Add prod flag to generate-disclaimer
  packages/mobile/package.json
Labels: automerge

#511 Revert broken verification changes in 1.15.1
  packages/mobile/docs/verification_state_machine.plantuml
  packages/mobile/docs/verification_state_machine.png
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/src/account/Settings.test.tsx
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/app/saga.test.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/app/selectors.test.ts
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/app/verificationMigration.test.ts
  packages/mobile/src/app/verificationMigration.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/feelessVerificationErrors.ts
  packages/mobile/src/identity/privateHashing.test.ts
  packages/mobile/src/identity/privateHashing.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/revoke.ts
  packages/mobile/src/identity/saga.ts
  packages/mobile/src/identity/smsRetrieval.ts
  packages/mobile/src/identity/types.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/reducers.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/src/send/Send.test.tsx
  packages/mobile/src/verify/VerificationCodeInput.test.tsx
  packages/mobile/src/verify/VerificationCodeInput.tsx
  packages/mobile/src/verify/VerificationEducationScreen.test.tsx
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/VerificationFailedModal.tsx
  packages/mobile/src/verify/VerificationInputScreen.test.tsx
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.test.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/mobile/src/verify/komenci.test.ts
  packages/mobile/src/verify/komenci.ts
  packages/mobile/src/verify/module.ts
  packages/mobile/src/verify/reducer.ts
  packages/mobile/src/verify/requestAttestations.test.ts
  packages/mobile/src/verify/requestAttestations.ts
  packages/mobile/src/verify/revealAttestations.test.ts
  packages/mobile/src/verify/revealAttestations.ts
  packages/mobile/src/verify/saga.test.ts
  packages/mobile/src/verify/saga.ts
  packages/mobile/src/verify/sagas/resetKomenciSessionSaga.ts
  packages/mobile/test/schemas.ts
  packages/mobile/test/values.ts
Labels: automerge

#517 Add Analytics for warning modal when sending to an address
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/recipients/RecipientPicker.tsx
  packages/mobile/src/send/SendToAddressWarning.tsx
Labels: automerge

#542 Add cEUR exchanges to feed on Blockchain API
  packages/blockchain-api/src/blockscout.ts
  packages/blockchain-api/src/events/ExchangeContractCall.ts
  packages/blockchain-api/src/events/ExchangeTokenToCelo.ts
  packages/blockchain-api/src/helpers/EventBuilder.ts
  packages/blockchain-api/src/utils.ts
  packages/blockchain-api/test/InputDecoder.test.ts
  packages/blockchain-api/test/blockscout.test.ts
Labels: automerge

#536 Update nvmrc to 12.22.1
  .nvmrc
Labels: automerge

#440 Add bottom menu when shake for support
  packages/mobile/e2e/src/usecases/Support.js
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/src/account/ShakeForSupport.test.tsx
  packages/mobile/src/account/ShakeForSupport.tsx
  packages/mobile/src/account/__snapshots__/ShakeForSupport.test.tsx.snap
  packages/mobile/src/navigator/NavigatorWrapper.tsx
Labels: TestQuality, automerge, requirement

#642 Revert broken verification changes in 1.15.1
  packages/mobile/docs/verification_state_machine.plantuml
  packages/mobile/docs/verification_state_machine.png
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/src/account/Settings.test.tsx
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/app/saga.test.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/app/selectors.test.ts
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/app/verificationMigration.test.ts
  packages/mobile/src/app/verificationMigration.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/feelessVerificationErrors.ts
  packages/mobile/src/identity/privateHashing.test.ts
  packages/mobile/src/identity/privateHashing.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/revoke.ts
  packages/mobile/src/identity/saga.ts
  packages/mobile/src/identity/smsRetrieval.ts
  packages/mobile/src/identity/types.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/reducers.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/src/send/Send.test.tsx
  packages/mobile/src/verify/VerificationCodeInput.test.tsx
  packages/mobile/src/verify/VerificationCodeInput.tsx
  packages/mobile/src/verify/VerificationEducationScreen.test.tsx
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/VerificationFailedModal.tsx
  packages/mobile/src/verify/VerificationInputScreen.test.tsx
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.test.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/mobile/src/verify/komenci.test.ts
  packages/mobile/src/verify/komenci.ts
  packages/mobile/src/verify/module.ts
  packages/mobile/src/verify/reducer.ts
  packages/mobile/src/verify/requestAttestations.test.ts
  packages/mobile/src/verify/requestAttestations.ts
  packages/mobile/src/verify/revealAttestations.test.ts
  packages/mobile/src/verify/revealAttestations.ts
  packages/mobile/src/verify/saga.test.ts
  packages/mobile/src/verify/saga.ts
  packages/mobile/src/verify/sagas/resetKomenciSessionSaga.ts
  packages/mobile/test/schemas.ts
  packages/mobile/test/values.ts
Labels: automerge

#643 Add more verification events
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/saga.test.ts
  packages/mobile/src/verify/saga.ts
Labels: automerge
