Repository valora-inc/wallet, pull requests merged in 2021-07, with the labels that each got.

#644 Bump version to 1.15.2
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
Labels: automerge

#541 test: upload junit test results with github actions
  .github/workflows/e2e.yml
Labels: Component: Tests, automerge, wallet

#653 Add cEUR transfer support to notification service
  packages/notification-service/app.alfajores.yaml
  packages/notification-service/app.mainnet.yaml
  packages/notification-service/locales/en.json
  packages/notification-service/src/blockscout/transfers.ts
  packages/notification-service/src/firebase.ts
  packages/notification-service/src/util/utils.ts
  packages/notification-service/test/transfers.test.ts
Labels: automerge

#658 Update text on rewards screen
  packages/mobile/locales/en-US/consumerIncentives.json
  packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.tsx
Labels: automerge

#654 Remove Flake Tracker and Setup Detox 18 in Wallet Repo
  package.json
  packages/mobile/e2e/config.json
  packages/mobile/e2e/environment.js
  packages/mobile/e2e/init.js
  packages/mobile/e2e/setup.js
  packages/mobile/e2e/src/usecases/SecureSend.js
  packages/mobile/e2e/src/usecases/Send.js
  packages/mobile/e2e/src/utils/celoEducation.js
  packages/mobile/e2e/src/utils/utils.js
  packages/mobile/package.json
  packages/mobile/scripts/run_e2e.sh
  yarn.lock
Labels: Component: Tests, automerge, tech-debt, wallet

#638 [WalletConnect] Expose eth_sendTransaction RPC
  packages/mobile/locales/en-US/walletConnect.json
  packages/mobile/src/walletConnect/constants.ts
  packages/mobile/src/walletConnect/saga.ts
Labels: automerge

#473 Allow opening in-app notifications in external browser
  packages/mobile/src/home/NotificationBox.test.tsx
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/reducers.ts
Labels: automerge

#459 Properly handling WalletConnect deep/universal links
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/ios/celo/celo.entitlements
  packages/mobile/src/app/saga.test.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/walletConnect/saga.ts
  packages/mobile/src/walletConnect/walletConnect.ts
Labels: automerge

#663 Detox Fixes for CI Pipeline
  packages/mobile/e2e/src/usecases/OffRamps.js
  packages/mobile/e2e/src/utils/utils.js
Labels: Component: Tests, automerge, wallet

#656 Show a different text in the feed for the new savings rewards
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/src/config.ts
  packages/mobile/src/firebase/db-rules.json
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/identity/contactMapping.test.ts
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/recipients/actions.ts
  packages/mobile/src/recipients/reducer.ts
  packages/mobile/src/recipients/saga.ts
  packages/mobile/src/redux/sagas.ts
  packages/mobile/src/send/utils.ts
  packages/mobile/src/transactions/TransactionReview.tsx
  packages/mobile/src/transactions/TransferConfirmationCard.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/mobile/src/transactions/saga.ts
  packages/mobile/src/transactions/transferFeedUtils.ts
  packages/mobile/src/transactions/utils.ts
  packages/mobile/test/schemas.ts
  packages/mobile/test/utils.ts
Labels: automerge

#651 Update push notification for rewards distribution
  packages/notification-service/locales/en.json
  packages/notification-service/src/firebase.ts
  packages/notification-service/test/firebase.test.ts
Labels: automerge

#640 Enable cEUR cash-in
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/app/reducers.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.test.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeOptions.test.tsx.snap
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/localCurrency/hooks.ts
  packages/mobile/src/navigator/Headers.tsx
  packages/mobile/src/utils/currencies.ts
  packages/mobile/test/schemas.ts
Labels: TestQuality, automerge, requirement

#838 Fix crash due to redux immutability
  packages/mobile/src/transactions/transferFeedUtils.ts
Labels: automerge

#853 [BlockchainApi] Fix feed error when local currency is EUR
  packages/blockchain-api/src/currencyConversion/CurrencyConversionAPI.test.ts
  packages/blockchain-api/src/currencyConversion/CurrencyConversionAPI.ts
Labels: automerge

#856 Hide keyboard when selecting currency to exchange
  packages/mobile/src/exchange/ExchangeScreenHeader.tsx
Labels: automerge

#857 Show 0.00 instead of <0.000 when an amount is exactly 0
  packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap
  packages/mobile/src/import/__snapshots__/ImportWallet.test.tsx.snap
  packages/mobile/src/utils/formatting.ts
Labels: automerge

#858 E2E test improvements / CI fixes
  packages/mobile/e2e/init.js
  packages/mobile/e2e/src/usecases/OffRamps.js
  packages/mobile/e2e/src/usecases/OnRamps.js
  packages/mobile/e2e/src/usecases/SecureSend.js
  packages/mobile/e2e/src/usecases/Send.js
  packages/mobile/scripts/run_e2e.sh
Labels: automerge

#861 Make account number Tap to Copy link touchable
  packages/mobile/src/components/AccountNumber.tsx
  packages/mobile/src/components/__snapshots__/AccountNumber.test.tsx.snap
  packages/mobile/src/fiatExchanges/ExternalExchanges.tsx
  packages/mobile/src/navigator/DrawerNavigator.tsx
  packages/mobile/src/transactions/UserSection.tsx
Labels: wallet

#868 Fix clock sync
  packages/mobile/src/utils/time.ts
Labels: automerge

#539 Android Config for GitHub Actions
  .github/workflows/e2e.yml
  package.json
  packages/mobile/e2e/README.md
  packages/mobile/e2e/init.js
  packages/mobile/e2e/src/usecases/ExchangeCelo.js
  packages/mobile/e2e/src/usecases/HandleDeepLinkDappkit.js
  packages/mobile/e2e/src/usecases/HandleDeepLinkSend.js
  packages/mobile/e2e/src/usecases/HandleNotification.js
  packages/mobile/e2e/src/usecases/NewAccountOnboarding.js
  packages/mobile/e2e/src/usecases/OffRamps.js
  packages/mobile/e2e/src/usecases/OnRamps.js
  packages/mobile/e2e/src/usecases/ResetAccount.js
  packages/mobile/e2e/src/usecases/RestoreAccountOnboarding.js
  packages/mobile/e2e/src/usecases/SecureSend.js
  packages/mobile/e2e/src/usecases/Send.js
  packages/mobile/e2e/src/usecases/Settings.js
  packages/mobile/e2e/src/usecases/Support.js
  packages/mobile/e2e/src/utils/retries.js
  packages/mobile/package.json
  yarn.lock
Labels: Component: Tests, automerge, wallet

#863 Transaction Feed Accessibility
  packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
  packages/mobile/src/components/CurrencyDisplay.tsx
  packages/mobile/src/components/__snapshots__/TokenBottomSheet.test.tsx.snap
  packages/mobile/src/components/__snapshots__/TotalLineItem.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListItem.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListScreen.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentReminderSummaryNotification.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationCard.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/CeloGoldOverview.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeConfirmationCard.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeHomeScreen.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeReview.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/WithdrawCeloReviewScreen.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/WithdrawCeloSummary.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/ProviderOptionsScreen.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/ReviewFees.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/SimplexScreen.test.tsx.snap
  packages/mobile/src/import/__snapshots__/ImportWallet.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestConfirmation.test.tsx.snap
  packages/mobile/src/recipients/RecipientItem.tsx
  packages/mobile/src/recipients/__snapshots__/RecipientItem.test.tsx.snap
  packages/mobile/src/send/__snapshots__/Send.test.tsx.snap
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/transactions/CeloTransferFeedItem.tsx
  packages/mobile/src/transactions/GoldTransactionFeedItem.tsx
  packages/mobile/src/transactions/TransactionFeedItem.tsx
  packages/mobile/src/transactions/__snapshots__/CeloTransferFeedItem.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/ExchangeFeedItem.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/GoldTransactionFeedItem.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransactionFeed.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransactionsList.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransferConfirmationCard.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransferFeedItem.test.tsx.snap
Labels: Component: Feed & Notifications, automerge, tech-debt, wallet

#855 CTA Localization / Text Accessibility
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListItem.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListScreen.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentReminderSummaryNotification.test.tsx.snap
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/notifications/__snapshots__/SummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestSummaryNotification.test.tsx.snap
  packages/react-components/components/CallToActionsBar.tsx
  packages/react-components/components/MessagingCard.tsx
Labels: Component: Feed & Notifications, automerge, tech-debt, wallet

#836 Account Key Accessibility
  packages/mobile/src/backup/BackupIntroduction.tsx
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
Labels: Component: Account Recovery, automerge, tech-debt, wallet

#877 Enable Get Attributes for Android E2E Tests
  packages/mobile/android/app/build.gradle
  packages/mobile/e2e/src/usecases/NewAccountOnboarding.js
Labels: Component: Tests, android, tech-debt, wallet

#862 Education Localization & Accessibility
  packages/mobile/src/account/Education.tsx
  packages/mobile/src/account/__snapshots__/AccountKeyEducation.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Education.test.tsx.snap
  packages/mobile/src/account/__snapshots__/GoldEducation.test.tsx.snap
  packages/mobile/src/onboarding/welcome/Welcome.tsx
Labels: Component: Onboarding, automerge, tech-debt, wallet

#886 Remove Circle Ci Tasks
  .circleci/config.yml
Labels: Component: Tests, automerge, tech-debt, wallet

#639 Make unencrypted comment warning text more visible
  packages/mobile/src/send/SendConfirmation.tsx
  packages/react-components/styles/colors.tsx
Labels: automerge

#891 Update debug logging redux blocklist
  packages/mobile/src/pincode/authentication.ts
  packages/mobile/src/redux/sagas.ts
Labels: automerge

#889 Add CICO success event
  packages/cloud-functions/package.json
  packages/cloud-functions/src/cico/composeProviderUrl.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/fiatExchanges/CashInSuccess.tsx
  packages/mobile/src/fiatExchanges/saga.ts
  yarn.lock
Labels: automerge

#894 Change GitHub Actions workflow names
  .github/workflows/check.yml
  .github/workflows/e2e.yml
  .github/workflows/test.yml
Labels: tech-debt

#904 Remove VSCode configs for packages no longer in the repo
  .vscode/launch.json
Labels: tech-debt

#903 Delete cli-standalone Docker file because this package is not in the wallet repo
  dockerfiles/cli-standalone/Dockerfile
Labels: tech-debt

#901 Delete attestation-service Docker file because this package is not in the wallet repo
  dockerfiles/attestation-service/Dockerfile
Labels: tech-debt

#900 Delete celotool Docker file because this package is not in the wallet repo
  dockerfiles/celotool/Dockerfile
Labels: tech-debt

#898 Delete leaderboard Docker file because this package is not in the wallet repo
  dockerfiles/leaderboard/Dockerfile
Labels: tech-debt

#895 Delete .gitattributes since packages/docs is not in the wallet repo
  .gitattributes
Labels: tech-debt

#896 Delete phone number privacy Docker file because this package is not in the wallet repo
  dockerfiles/phone-number-privacy/Dockerfile
Labels: tech-debt

#897 Delete metadata-crawler Docker file because this package is not in the wallet repo
  dockerfiles/metadata-crawler/Dockerfile
Labels: tech-debt

#899 Delete cloudbuild Docker file because this package is not in the wallet repo
  dockerfiles/cloudbuild/Dockerfile
Labels: tech-debt

#902 Delete cli Docker file because this package is not in the wallet repo
  dockerfiles/cli/Dockerfile
Labels: tech-debt

#508 Automatically correct minor mnemonic phrase errors on import
  package.json
  packages/mobile/__mocks__/react-i18next.js
  packages/mobile/__mocks__/src/i18n.ts
  packages/mobile/locales/en-US/backupKeyFlow6.json
  packages/mobile/package.json
  packages/mobile/src/account/__snapshots__/RaiseLimitScreen.test.tsx.snap
  packages/mobile/src/alert/actions.ts
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/backup/BackupComplete.tsx
  packages/mobile/src/backup/BackupIntroduction.tsx
  packages/mobile/src/backup/utils.test.ts
  packages/mobile/src/backup/utils.ts
  packages/mobile/src/components/__snapshots__/Avatar.test.tsx.snap
  packages/mobile/src/components/__snapshots__/TokenBottomSheet.test.tsx.snap
  packages/mobile/src/consumerIncentives/__snapshots__/ConsumerIncentivesHomeScreen.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListItem.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListScreen.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentReminderSummaryNotification.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeReview.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.test.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
  packages/mobile/src/fiatExchanges/SimplexScreen.test.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/CashInSuccess.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/ReviewFees.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/SimplexScreen.test.tsx.snap
  packages/mobile/src/home/NotificationBox.test.tsx
  packages/mobile/src/home/WalletHome.test.tsx
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/import/ImportWallet.tsx
  packages/mobile/src/import/saga.test.ts
  packages/mobile/src/import/saga.ts
  packages/mobile/src/onboarding/registration/__snapshots__/RegulatoryTerms.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestConfirmation.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestUnavailable.test.tsx.snap
  packages/mobile/src/send/SendAmount/SendAmount.test.tsx
  packages/mobile/src/send/SendConfirmation.test.tsx
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/send/__snapshots__/ValidateRecipientAccount.test.tsx.snap
  packages/mobile/src/send/__snapshots__/ValidateRecipientIntro.test.tsx.snap
  packages/mobile/src/tokens/saga.ts
  packages/mobile/src/transactions/TransferFeedItem.test.tsx
  packages/mobile/src/transactions/__snapshots__/CeloTransferFeedItem.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/ExchangeFeedItem.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransactionFeed.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransactionsList.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransferFeedItem.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationInputScreen.test.tsx.snap
  scripts/hooks/pre-push.js
  yarn.lock
Labels: automerge

#909 Add mobile check
  .github/workflows/test.yml
  packages/mobile/package.json
Labels: Component: Tests, tech-debt, wallet

#910 Change all references to the account number to Account Address
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/nuxVerification2.json
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/en-US/walletConnect.json
  packages/mobile/src/send/ValidateRecipientAccount.tsx
Labels: automerge

#866 Misc Accessiblity
  packages/mobile/src/account/__snapshots__/AccountKeyEducation.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Education.test.tsx.snap
  packages/mobile/src/account/__snapshots__/GoldEducation.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Profile.test.tsx.snap
  packages/mobile/src/account/__snapshots__/RaiseLimitScreen.test.tsx.snap
  packages/mobile/src/account/__snapshots__/ShakeForSupport.test.tsx.snap
  packages/mobile/src/account/__snapshots__/SupportContact.test.tsx.snap
  packages/mobile/src/app/__snapshots__/Debug.test.tsx.snap
  packages/mobile/src/app/__snapshots__/ErrorScreen.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupForceScreen.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupPhrase.test.tsx.snap
  packages/mobile/src/components/ContactCircle.tsx
  packages/mobile/src/components/__snapshots__/Avatar.test.tsx.snap
  packages/mobile/src/consumerIncentives/__snapshots__/ConsumerIncentivesHomeScreen.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListItem.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListScreen.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentReminderSummaryNotification.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationCard.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/CeloExchangeButtons.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeHomeScreen.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeReview.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/WithdrawCeloReviewScreen.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/CashInSuccess.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeOptions.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/SimplexScreen.test.tsx.snap
  packages/mobile/src/geth/__snapshots__/GethAwareButton.test.tsx.snap
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/mobile/src/identity/__snapshots__/PhoneNumberLookupQuotaScreen.test.tsx.snap
  packages/mobile/src/import/__snapshots__/ImportWallet.test.tsx.snap
  packages/mobile/src/onboarding/contacts/__snapshots__/ImportContactsScreen.test.tsx.snap
  packages/mobile/src/onboarding/registration/PictureInput.tsx
  packages/mobile/src/onboarding/registration/__snapshots__/NameAndPicture.test.tsx.snap
  packages/mobile/src/onboarding/registration/__snapshots__/RegulatoryTerms.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestConfirmation.test.tsx.snap
  packages/mobile/src/qrcode/__snapshots__/QRCode.test.tsx.snap
  packages/mobile/src/recipients/__snapshots__/RecipientItem.test.tsx.snap
  packages/mobile/src/send/__snapshots__/Send.test.tsx.snap
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/send/__snapshots__/ValidateRecipientAccount.test.tsx.snap
  packages/mobile/src/send/__snapshots__/ValidateRecipientIntro.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransferConfirmationCard.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransferFeedItem.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationLoadingScreen.test.tsx.snap
  packages/react-components/components/Button.tsx
  packages/react-components/components/WithTextSearchPasteAware.tsx
  packages/react-components/components/__snapshots__/Button.test.tsx.snap
  packages/react-components/components/__snapshots__/FullscreenCTA.test.tsx.snap
Labels: Component: Other, Component: Send/Request, automerge, tech-debt, wallet

#915 [Wallet] Merge 1.16.2 release
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/package.json
Labels: automerge

#911 Delete CircleCI config
  .circleci/config.yml
  README.md
Labels: Component: Tests, tech-debt, wallet

#916 Update terms screen copy
  packages/mobile/locales/en-US/nuxNamePin1.json
  packages/mobile/src/onboarding/registration/RegulatoryTerms.tsx
  packages/mobile/src/onboarding/registration/__snapshots__/RegulatoryTerms.test.tsx.snap
Labels: automerge

#890 Refactor CICO event webhooks to save data to base tables
  packages/cloud-functions/jest_setup.ts
  packages/cloud-functions/src/bigQuery.ts
  packages/cloud-functions/src/cico/moonpayWebhook.schema.sql
  packages/cloud-functions/src/cico/moonpayWebhook.test.ts
  packages/cloud-functions/src/cico/moonpayWebhook.ts
  packages/cloud-functions/src/cico/rampWebhook.schema.sql
  packages/cloud-functions/src/cico/rampWebhook.test.ts
  packages/cloud-functions/src/cico/rampWebhook.ts
  packages/cloud-functions/src/cico/transakWebhook.schema.sql
  packages/cloud-functions/src/cico/transakWebhook.ts
  packages/cloud-functions/src/cico/utils.ts
Labels: automerge

#917 Add Xanpool event webhook
  packages/cloud-functions/src/cico/transakWebhook.schema.sql
  packages/cloud-functions/src/cico/xanpoolWebhook.schema.sql
  packages/cloud-functions/src/cico/xanpoolWebhook.test.ts
  packages/cloud-functions/src/cico/xanpoolWebhook.ts
  packages/cloud-functions/src/index.ts
Labels: automerge

#920 Simplex event polling
  packages/cloud-functions/.env.alfajores.enc
  packages/cloud-functions/.env.mainnet.enc
  packages/cloud-functions/firebase-env-config.sh
  packages/cloud-functions/jest_setup.ts
  packages/cloud-functions/src/cico/Simplex.ts
  packages/cloud-functions/src/cico/moonpayWebhook.test.ts
  packages/cloud-functions/src/cico/rampWebhook.test.ts
  packages/cloud-functions/src/cico/simplexEventPolling.schema.sql
  packages/cloud-functions/src/cico/simplexEventPolling.test.ts
  packages/cloud-functions/src/cico/simplexEventPolling.ts
  packages/cloud-functions/src/cico/utils.ts
  packages/cloud-functions/src/config.ts
  packages/cloud-functions/src/index.ts
Labels: automerge

#924 Remove mobile test suite from vulnerabilities check
  .github/workflows/check.yml
Labels: Component: Tests, tech-debt

#892 Report availability of Google and Huawei Mobile Services
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/app/actions.ts
  packages/mobile/src/app/reducers.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/redux/sagas.ts
  packages/mobile/src/utils/permissions.android.ts
  packages/mobile/src/utils/permissions.ios.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#926 Change NotificationBox to a functional component
  packages/mobile/src/fiatExchanges/__snapshots__/ProviderOptionsScreen.test.tsx.snap
  packages/mobile/src/home/NotificationBox.tsx
Labels: automerge

#928 CICO firebase function event log parser
  packages/cloud-functions/src/bigQuery.ts
  packages/cloud-functions/src/cico/logParser/parseEventLogs.ts
  packages/cloud-functions/src/cico/rampWebhook.ts
  packages/cloud-functions/src/cico/transakWebhook.schema.sql
  packages/cloud-functions/src/cico/transakWebhook.ts
  packages/cloud-functions/src/cico/xanpoolWebhook.ts
  packages/cloud-functions/src/config.ts
Labels: automerge

#933 Update Simplex country restrictions & fix cloud-function package yarn.lock
  packages/cloud-functions/src/cico/Moonpay.ts
  packages/cloud-functions/src/cico/Ramp.ts
  packages/cloud-functions/src/cico/providerAvailability.ts
  packages/cloud-functions/yarn.lock
Labels: automerge
