Repository valora-inc/wallet, pull requests merged in 2021-03, with the labels that each got.

#47 Run e2e tests in release mode
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
Labels: automerge

#48 Use priority normal for android notifications
  packages/notification-service/src/firebase.ts
Labels: automerge

#73 Add proguard rules for InAppBrowser on Android
  packages/mobile/android/app/proguard-rules.pro
Labels: automerge

#72 Change the way cutoff for rewards is calculated
  packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.tsx
  packages/mobile/src/utils/time.ts
Labels: automerge

#75 Update contractkit to 1.0.2
  packages/komencikit/package.json
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#67 Add UI for invite rewards
  packages/mobile/branding/celo/src/icons/Logo.tsx
  packages/mobile/locales/en-US/inviteFlow11.json
  packages/mobile/locales/es-419/inviteFlow11.json
  packages/mobile/locales/pt-BR/inviteFlow11.json
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/src/app/actions.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/icons/Invite.tsx
  packages/mobile/src/recipients/RecipientItem.tsx
  packages/mobile/src/recipients/__snapshots__/RecipientItem.test.tsx.snap
  packages/mobile/src/send/GetRewardPill.tsx
  packages/mobile/src/send/InviteRewardsBanner.tsx
  packages/mobile/src/send/Send.test.tsx
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/send/__snapshots__/Send.test.tsx.snap
  packages/mobile/src/send/reducers.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#69 Enable card payments on Ramp
  packages/mobile/secrets.json.enc
  packages/mobile/src/config.ts
  packages/mobile/src/fiatExchanges/RampScreen.tsx
  packages/mobile/src/geth/networkConfig.ts
Labels: automerge

#90 Add CELO txs to the main feed
  packages/blockchain-api/src/blockscout.ts
  packages/blockchain-api/src/events/ExchangeCeloToToken.ts
  packages/blockchain-api/src/events/ExchangeTokenToCelo.ts
  packages/blockchain-api/src/schema.ts
  packages/blockchain-api/src/transaction/TransactionType.ts
  packages/blockchain-api/test/blockscout.test.ts
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/es-419/walletFlow5.json
  packages/mobile/locales/pt-BR/walletFlow5.json
  packages/mobile/src/exchange/ExchangeHomeScreen.tsx
  packages/mobile/src/home/WalletHome.tsx
  packages/mobile/src/transactions/CeloTransferFeedItem.tsx
  packages/mobile/src/transactions/ExchangeFeedItem.tsx
  packages/mobile/src/transactions/TransactionFeed.tsx
  packages/mobile/src/transactions/TransactionFeedItem.tsx
  packages/mobile/src/transactions/TransactionsList.test.tsx
  packages/mobile/src/transactions/TransactionsList.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/mobile/src/transactions/__snapshots__/CeloTransferFeedItem.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/ExchangeFeedItem.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransactionFeed.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransactionsList.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransferFeedItem.test.tsx.snap
  packages/mobile/src/transactions/transferFeedUtils.ts
Labels: automerge

#93 Scripts to test push notifications in doze mode on android
  packages/mobile/scripts/doze.sh
  packages/mobile/scripts/push.sh
Labels: automerge

#40 Improve notification-service notification sending
  packages/notification-service/config/config.alfajoresstaging.env
  packages/notification-service/config/config.integration.env
  packages/notification-service/config/config.local.env
  packages/notification-service/config/config.pilot.env
  packages/notification-service/config/config.pilotstaging.env
  packages/notification-service/src/blockscout/blockscout.d.ts
  packages/notification-service/src/blockscout/decode.ts
  packages/notification-service/src/blockscout/nativeTransfersFormatter.ts
  packages/notification-service/src/blockscout/transfers.ts
  packages/notification-service/src/blockscout/transfersFormatter.ts
  packages/notification-service/src/firebase.ts
  packages/notification-service/test/decode.test.ts
  packages/notification-service/test/firebase.test.ts
  packages/notification-service/test/transfers.test.ts
  packages/notification-service/test/transfersFormatter.test.ts
Labels: automerge

#74 Move CICO provider url composition server-side
  .gitignore
  packages/mobile/secrets.json.enc
  packages/mobile/src/components/InAppBrowser.tsx
  packages/mobile/src/config.ts
  packages/mobile/src/fiatExchanges/MoonPay.test.tsx
  packages/mobile/src/fiatExchanges/MoonPayScreen.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/RampScreen.tsx
  packages/mobile/src/fiatExchanges/TransakScreen.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/MoonPay.test.tsx.snap
  packages/mobile/src/fiatExchanges/utils.tsx
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/navigator/types.tsx
  packages/moonpay-auth/README.md
  packages/provider-url-service/.env.alfajores.enc
  packages/provider-url-service/.env.mainnet.enc
  packages/provider-url-service/.firebaserc
  packages/provider-url-service/.gitignore
  packages/provider-url-service/firebase-env-config.sh
  packages/provider-url-service/firebase.json
  packages/provider-url-service/package.json
  packages/provider-url-service/src/config.ts
  packages/provider-url-service/src/index.ts
  packages/provider-url-service/tsconfig.json
  packages/provider-url-service/tslint.json
  packages/provider-url-service/yarn.lock
  scripts/key_placer.sh
Labels: automerge

#76 fix: verify-to-confirm
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/inviteFlow11.json
  packages/mobile/locales/en-US/nuxNamePin1.json
  packages/mobile/locales/en-US/nuxVerification2.json
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/en-US/paymentRequestFlow.json
  packages/mobile/locales/en-US/receiveFlow8.json
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/inviteFlow11.json
  packages/mobile/locales/es-419/nuxNamePin1.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/locales/es-419/paymentRequestFlow.json
  packages/mobile/locales/es-419/receiveFlow8.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/locales/es-419/walletFlow5.json
  packages/mobile/locales/pt-BR/global.json
  packages/mobile/locales/pt-BR/inviteFlow11.json
  packages/mobile/locales/pt-BR/nuxNamePin1.json
  packages/mobile/locales/pt-BR/nuxVerification2.json
  packages/mobile/locales/pt-BR/onboarding.json
  packages/mobile/locales/pt-BR/paymentRequestFlow.json
  packages/mobile/locales/pt-BR/receiveFlow8.json
  packages/mobile/locales/pt-BR/sendFlow7.json
  packages/mobile/locales/pt-BR/walletFlow5.json
Labels: automerge

#104 Upgrade firebase packages to 11.0.0
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/firebase/saga.ts
  packages/mobile/src/paymentRequest/saga.ts
  patches/@react-native-firebase/database+6.7.1.patch
  yarn.lock
Labels: automerge

#102 Warn users if provider does not support current location
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/locales/es-419/fiatExchangeFlow.json
  packages/mobile/locales/pt-BR/fiatExchangeFlow.json
  packages/mobile/secrets.json.enc
  packages/mobile/src/config.ts
  packages/mobile/src/fiatExchanges/MoonPayScreen.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/RampScreen.tsx
  packages/mobile/src/fiatExchanges/TransakScreen.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/ProviderOptionsScreen.test.tsx.snap
  packages/mobile/src/fiatExchanges/utils.tsx
  packages/mobile/src/flags.ts
  packages/mobile/src/utils/countryFeatures.test.ts
  packages/provider-url-service/firebase-env-config.sh
  packages/provider-url-service/package.json
Labels: automerge

#118 Fix hash from branding repo
  packages/mobile/scripts/sync_branding.sh
Labels: automerge

#98 Add detailed events tracking to CICO flow
  packages/mobile/src/account/FiatExchange.tsx
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/components/AccountNumber.tsx
  packages/mobile/src/fiatExchanges/ExternalExchanges.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/fiatExchanges/FundingEducationDialog.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/Spend.tsx
Labels: Component: Add/Withdraw, automerge, wallet

#105 Upgrade firebase-admin
  packages/blockchain-api/package.json
  packages/moonpay-auth/package.json
  packages/notification-service/package.json
  packages/provider-url-service/package.json
  yarn.lock
Labels: automerge

#126 Add tests for non-wallet packages to CI
  .circleci/config.yml
  packages/blockchain-api/test/blockscout.test.ts
  packages/notification-service/test/firebase.test.ts
Labels: automerge

#121 Change copy for CELO transfers
  packages/notification-service/locales/en.json
  packages/notification-service/locales/es.json
  packages/notification-service/locales/pt.json
  packages/notification-service/src/firebase.ts
  packages/notification-service/test/firebase.test.ts
Labels: automerge

#122 Changed font size in FeeDrawer to regular (#111)
  packages/mobile/src/components/FeeDrawer.tsx
Labels: automerge, enhancement, wallet

#112 Translation management with Crowdin
  .circleci/config.yml
  crowdin.yml
  packages/mobile/README.md
  packages/mobile/locales/es-419/backupKeyFlow6.json
  packages/mobile/locales/es-419/dev.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/goldEducation.json
  packages/mobile/locales/es-419/nuxNamePin1.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/locales/pt-BR/goldEducation.json
Labels: automerge

#101 Get providers for tx hashes from Firebase
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/actions.ts
  packages/mobile/src/fiatExchanges/reducer.test.ts
  packages/mobile/src/fiatExchanges/reducer.ts
  packages/mobile/src/fiatExchanges/saga.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/store.ts
Labels: automerge

#117 Eliminate online gas estimation from send and invite flows
  packages/mobile/__mocks__/@celo/contractkit/index.ts
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/components/FeeDrawer.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationCard.test.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationCard.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationScreen.test.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationScreen.tsx
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/escrow/actions.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/exchange/WithdrawCeloScreen.test.tsx
  packages/mobile/src/exchange/WithdrawCeloScreen.tsx
  packages/mobile/src/exchange/saga.ts
  packages/mobile/src/fees/CalculateFee.tsx
  packages/mobile/src/fees/EstimateFee.tsx
  packages/mobile/src/fees/saga.ts
  packages/mobile/src/fees/selectors.ts
  packages/mobile/src/fiatExchanges/saga.test.ts
  packages/mobile/src/geth/consts.ts
  packages/mobile/src/goldToken/actions.ts
  packages/mobile/src/invite/actions.ts
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/localCurrency/convert.ts
  packages/mobile/src/networkInfo/selectors.ts
  packages/mobile/src/send/SendConfirmation.test.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/send/actions.ts
  packages/mobile/src/send/saga.ts
  packages/mobile/src/stableToken/actions.ts
  packages/mobile/src/stableToken/saga.test.ts
  packages/mobile/src/tokens/saga.ts
  packages/mobile/src/transactions/TransactionFeed.tsx
  packages/mobile/src/transactions/actions.ts
  packages/mobile/src/transactions/contract-utils.ts
  packages/mobile/src/transactions/saga.ts
  packages/mobile/src/transactions/send.ts
  packages/mobile/src/utils/formatting.ts
  packages/mobile/src/web3/contracts.ts
  packages/mobile/src/web3/gas.ts
  packages/mobile/src/web3/selectors.ts
  packages/mobile/src/web3/utils.ts
Labels: automerge

#125 [Wallet] Adjust integration
  packages/mobile/.env.alfajores
  packages/mobile/.env.alfajoresdev
  packages/mobile/.env.mainnet
  packages/mobile/.env.mainnetdev
  packages/mobile/.env.test
  packages/mobile/.gitignore
  packages/mobile/__mocks__/secrets.json
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/jest.config.js
  packages/mobile/package.json
  packages/mobile/secrets.json.enc
  packages/mobile/secrets.json.template
  packages/mobile/src/analytics/ValoraAnalytics.ts
  packages/mobile/src/config.ts
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
  patches/@segment+analytics-react-native+1.3.2.patch
  yarn.lock
Labels: automerge

#137 [Wallet] Merge back 1.11.1 changes
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
Labels: automerge

#139 Update celo sdk
  packages/blockchain-api/package.json
  packages/komencikit/package.json
  packages/mobile/package.json
  packages/notification-service/package.json
  packages/react-components/package.json
  yarn.lock
Labels: automerge

#145 Enable CELO cash-in for all users
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeOptions.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/ProviderOptionsScreen.test.tsx.snap
  packages/mobile/src/fiatExchanges/utils.tsx
Labels: automerge

#147 Disable OTP keyboard suggestion on iOS
  packages/mobile/src/components/CodeInput.tsx
  packages/mobile/src/components/__snapshots__/CodeInput.test.tsx.snap
Labels: automerge

#163 Display escrow payment details
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
Labels: automerge

#107 Create a success page after cash in
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/src/app/saga.ts
  packages/mobile/src/fiatExchanges/CashInSuccess.test.tsx
  packages/mobile/src/fiatExchanges/CashInSuccess.tsx
  packages/mobile/src/fiatExchanges/MoonPayScreen.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/RampScreen.tsx
  packages/mobile/src/fiatExchanges/TransakScreen.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/CashInSuccess.test.tsx.snap
  packages/mobile/src/fiatExchanges/actions.ts
  packages/mobile/src/fiatExchanges/reducer.test.ts
  packages/mobile/src/fiatExchanges/reducer.ts
  packages/mobile/src/fiatExchanges/utils.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/redux/migrations.test.ts
  packages/provider-url-service/src/index.ts
Labels: automerge

#168 Edits to CICO success screen
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/src/fiatExchanges/CashInSuccess.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/CashInSuccess.test.tsx.snap
Labels: automerge

#108 Split card and card options on cash in
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/locales/es-419/fiatExchangeFlow.json
  packages/mobile/locales/pt-BR/fiatExchangeFlow.json
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.test.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeOptions.test.tsx.snap
  packages/mobile/src/navigator/types.tsx
Labels: automerge

#170 Re-enable Transak
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/ProviderOptionsScreen.test.tsx.snap
Labels: automerge

#173 Increase the default transaction limit from $500 to $1000
  packages/mobile/locales/en-US/nuxNamePin1.json
  packages/mobile/locales/es-419/nuxNamePin1.json
  packages/mobile/locales/pt-BR/nuxNamePin1.json
  packages/mobile/src/account/reducer.test.ts
  packages/mobile/src/config.ts
  packages/mobile/src/onboarding/registration/RegulatoryTerms.tsx
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/send/SendAmount.test.tsx
Labels: automerge

#140 [Wallet] Portuguese seed phrases
  packages/mobile/__mocks__/react-native-securerandom.ts
  packages/mobile/src/backup/utils.test.ts
  packages/mobile/src/backup/utils.ts
  packages/mobile/src/web3/saga.test.ts
  packages/mobile/src/web3/saga.ts
Labels: automerge
