Repository valora-inc/wallet, pull requests merged in 2021-04, with the labels that each got.

#186 Bump to 1.12.1
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/account/LicenseDisclaimer.txt
Labels: automerge

#5 Unify komenci and classic verification flows
  packages/mobile/docs/verification_state_machine.plantuml
  packages/mobile/docs/verification_state_machine.png
  packages/mobile/package.json
  packages/mobile/src/account/Settings.test.tsx
  packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/app/selectors.test.ts
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/config.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/home/NotificationBox.test.tsx
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/feelessVerification.ts
  packages/mobile/src/identity/feelessVerificationErrors.ts
  packages/mobile/src/identity/privateHashing.test.ts
  packages/mobile/src/identity/privateHashing.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/revoke.ts
  packages/mobile/src/identity/saga.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/import/saga.ts
  packages/mobile/src/navigator/NavigatorWrapper.tsx
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/reducers.ts
  packages/mobile/src/redux/sagas.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/src/verify/VerificationCodeInput.tsx
  packages/mobile/src/verify/VerificationEducationScreen.test.tsx
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
  packages/mobile/src/verify/reducer.ts
  packages/mobile/src/verify/saga.test.ts
  packages/mobile/src/verify/saga.ts
  packages/mobile/test/schemas.ts
  yarn.lock
Labels: automerge

#188 Fix persist config version and add test
  packages/mobile/src/redux/store.test.ts
  packages/mobile/src/redux/store.ts
Labels: automerge

#194 Make some performance improvements to notification-service
  packages/notification-service/src/blockscout/transfers.ts
  packages/notification-service/src/firebase.ts
Labels: automerge

#195 Add flow for recovering access to account if Redux store is wiped
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/account/StoreWipeRecoveryScreen.tsx
  packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
  packages/mobile/src/account/actions.ts
  packages/mobile/src/account/reducer.ts
  packages/mobile/src/account/saga.ts
  packages/mobile/src/account/selectors.ts
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/import/ImportWallet.test.tsx
  packages/mobile/src/import/ImportWallet.tsx
  packages/mobile/src/import/saga.test.ts
  packages/mobile/src/import/saga.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/onboarding/registration/NameAndPicture.tsx
  packages/mobile/src/pincode/PincodeEnter.tsx
  packages/mobile/src/pincode/authentication.ts
  packages/mobile/src/utils/accountChecker.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#196 Verification Hotfixes
  packages/mobile/__mocks__/src/verify/hooks.ts
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/pt-BR/global.json
  packages/mobile/package.json
  packages/mobile/src/account/selectors.ts
  packages/mobile/src/app/reducers.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/home/selectors.ts
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/onboarding/registration/NameAndPicture.tsx
  packages/mobile/src/pincode/PincodeSet.test.tsx
  packages/mobile/src/pincode/PincodeSet.tsx
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/utils/countryFeatures.ts
  packages/mobile/src/verify/VerificationEducationScreen.test.tsx
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
  packages/mobile/src/verify/hooks.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#200 Fix account initialization in Hotfix PR
  packages/mobile/e2e/src/FundedAccount.spec.js
  packages/mobile/e2e/src/usecases/Send.js
  packages/mobile/e2e/src/utils/utils.js
  packages/mobile/src/pincode/PincodeSet.tsx
  packages/mobile/src/verify/VerificationEducationScreen.tsx
Labels: automerge

#202 Version bump to 1.12.2
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
Labels: automerge

#203 Choose language before starting recovery flow
  packages/mobile/src/account/StoreWipeRecoveryScreen.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/utils/accountChecker.ts
  packages/mobile/src/utils/contentTranslations.ts
Labels: automerge

#222 Fix analytics `drawer_navigation` event
  packages/mobile/src/navigator/DrawerNavigator.tsx
Labels: automerge

#220 test: add jest-html and jest-junit reporters
  .circleci/config.yml
  package.json
  packages/mobile/.gitignore
  packages/mobile/e2e/config.json
  yarn.lock
Labels: Component: Tests, automerge

#232 Remove @i1skn from the code owners list
  .github/CODEOWNERS
Labels: automerge

#176 Send push notification when someone withdraws from Escrow
  packages/notification-service/locales/en.json
  packages/notification-service/src/config.ts
  packages/notification-service/src/firebase.ts
  packages/notification-service/src/index.ts
  packages/notification-service/src/invites/invites.ts
  packages/notification-service/src/polling.ts
Labels: automerge

#234 Force y18n version 5.0.5
  package.json
  yarn.lock
Labels: automerge

#209 Add local providers remotely
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/src/app/reducers.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/config.ts
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.test.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.test.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/fiatExchanges/LocalProviderCashOut.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeOptions.test.tsx.snap
  packages/mobile/src/fiatExchanges/utils.tsx
  packages/mobile/src/firebase/db-rules.json
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/flags.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/src/utils/countryFeatures.test.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#162 Fix for tapping on a push notification on android
  packages/mobile/e2e/src/Notifications.spec.js
  packages/mobile/e2e/src/usecases/HandleNotification.js
  packages/mobile/src/app/App.tsx
  packages/mobile/src/app/actions.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/firebase/saga.ts
Labels: automerge

#242 Fix for toUpperCase error
  packages/mobile/src/recipients/recipient.ts
Labels: automerge

#81 Beginning to edit READ.me for new repo
  README.md
Labels: automerge

#255 Fix the fetching of exchange rates
  packages/mobile/src/exchange/reducer.ts
  packages/mobile/src/firebase/saga.ts
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/store.ts
Labels: automerge

#219 Add KYC status screen
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/src/account/RaiseLimitScreen.test.tsx
  packages/mobile/src/account/RaiseLimitScreen.tsx
  packages/mobile/src/account/Support.test.tsx
  packages/mobile/src/account/Support.tsx
  packages/mobile/src/account/SupportContact.tsx
  packages/mobile/src/account/__snapshots__/RaiseLimitScreen.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Support.test.tsx.snap
  packages/mobile/src/account/actions.ts
  packages/mobile/src/account/emailSender.test.tsx
  packages/mobile/src/account/emailSender.ts
  packages/mobile/src/account/reducer.ts
  packages/mobile/src/account/selectors.ts
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/app/reducers.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/firebase/db-rules.json
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/icons/ApprovedIcon.tsx
  packages/mobile/src/icons/DeniedIcon.tsx
  packages/mobile/src/icons/InProgressIcon.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/test/schemas.ts
Labels: automerge

#238 Xanpool integration
  packages/mobile/locales/en-US/global.json
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.test.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/XanpoolScreen.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/ProviderOptionsScreen.test.tsx.snap
  packages/mobile/src/fiatExchanges/reducer.ts
  packages/mobile/src/fiatExchanges/utils.tsx
  packages/mobile/src/flags.ts
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/provider-url-service/.env.alfajores.enc
  packages/provider-url-service/.env.mainnet.enc
  packages/provider-url-service/firebase-env-config.sh
  packages/provider-url-service/src/config.ts
  packages/provider-url-service/src/index.ts
Labels: automerge

#244 Notification Service: Only update last notified block if an event was found
  packages/notification-service/src/invites/invites.ts
  packages/notification-service/test/invites.test.ts
Labels: automerge

#266 add if outgoing payment request, remove header title with balance
  packages/mobile/src/send/SendAmount.tsx
Labels: automerge

#172 Update Prettier
  package.json
  packages/flake-tracker/src/db.js
  packages/flake-tracker/src/mocha/reporter.js
  packages/komencikit/src/retry.ts
  packages/mobile/__mocks__/@celo/identity/index.ts
  packages/mobile/__mocks__/react-native-analytics-segment-io.js
  packages/mobile/__mocks__/src/pincode/authentication.ts
  packages/mobile/e2e/src/utils/banners.js
  packages/mobile/src/app/saga.test.ts
  packages/mobile/src/backup/utils.ts
  packages/mobile/src/exchange/saga.test.ts
  packages/mobile/src/fees/saga.test.ts
  packages/mobile/src/fiatExchanges/utils.tsx
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/firebase/saga.ts
  packages/mobile/src/geth/GethNativeBridgeWallet.ts
  packages/mobile/src/geth/geth.ts
  packages/mobile/src/geth/saga.test.ts
  packages/mobile/src/identity/feelessVerificationErrors.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/paymentRequest/saga.ts
  packages/mobile/src/tokens/saga.ts
  packages/mobile/src/transactions/saga.ts
  packages/mobile/src/transactions/send.ts
  packages/mobile/src/utils/LogUploader.ts
  packages/mobile/src/utils/image.ts
  packages/mobile/src/utils/time.ts
  packages/mobile/src/verify/safety/GoogleReCaptcha.tsx
  packages/notification-service/src/blockscout/transfers.ts
  packages/react-components/__mocks__/react-native-analytics-segment-io.js
  packages/react-components/components/SimpleMessagingCard.tsx
  packages/typescript/custom-rules/noGlobalArrowFunctionsRule.js
  scripts/dependency-graph-utils.ts
  scripts/hooks/pre-push.js
  yarn.lock
Labels: automerge

#80 Simplex integration
  .gitignore
  packages/mobile/Gemfile.lock
  packages/mobile/ios/Podfile.lock
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/package.json
  packages/mobile/secrets.json.enc
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/config.ts
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.test.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/ReviewFees.test.tsx
  packages/mobile/src/fiatExchanges/ReviewFees.tsx
  packages/mobile/src/fiatExchanges/SimplexScreen.test.tsx
  packages/mobile/src/fiatExchanges/SimplexScreen.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/ProviderOptionsScreen.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/ReviewFees.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/SimplexScreen.test.tsx.snap
  packages/mobile/src/fiatExchanges/utils.tsx
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/types.tsx
  packages/provider-url-service/.env.alfajores.enc
  packages/provider-url-service/.env.mainnet.enc
  packages/provider-url-service/.firebaserc
  packages/provider-url-service/.gitignore
  packages/provider-url-service/firebase-env-config.sh
  packages/provider-url-service/package.json
  packages/provider-url-service/src/Simplex.ts
  packages/provider-url-service/src/config.ts
  packages/provider-url-service/src/index.ts
  packages/provider-url-service/src/utils.ts
  packages/provider-url-service/yarn.lock
  yarn.lock
Labels: automerge

#279 Fix sending of "invite received" notification
  packages/notification-service/src/config.ts
  packages/notification-service/src/firebase.ts
  packages/notification-service/src/invites/invites.ts
  packages/notification-service/src/polling.ts
Labels: automerge

#119 Add webhooks for MoonPay and Ramp
  .gitignore
  packages/cloud-functions/.env.alfajores.enc
  packages/cloud-functions/.env.mainnet.enc
  packages/cloud-functions/.firebaserc
  packages/cloud-functions/.gitignore
  packages/cloud-functions/config/rampProduction.pem.enc
  packages/cloud-functions/config/rampStaging.pem.enc
  packages/cloud-functions/deploy.sh
  packages/cloud-functions/firebase-env-config.sh
  packages/cloud-functions/firebase.json
  packages/cloud-functions/jest.config.js
  packages/cloud-functions/package.json
  packages/cloud-functions/src/cico/Provider.ts
  packages/cloud-functions/src/cico/Simplex.ts
  packages/cloud-functions/src/cico/composeCicoProviderUrl.ts
  packages/cloud-functions/src/cico/moonpayWebhook.test.ts
  packages/cloud-functions/src/cico/moonpayWebhook.ts
  packages/cloud-functions/src/cico/rampWebhook.test.ts
  packages/cloud-functions/src/cico/rampWebhook.ts
  packages/cloud-functions/src/cico/utils.ts
  packages/cloud-functions/src/config.ts
  packages/cloud-functions/src/firebase.ts
  packages/cloud-functions/src/index.ts
  packages/cloud-functions/tsconfig.json
  packages/cloud-functions/tslint.json
  packages/cloud-functions/yarn.lock
  packages/notification-service/src/firebase.ts
  packages/provider-url-service/.env.alfajores.enc
  packages/provider-url-service/.env.mainnet.enc
  scripts/key_placer.sh
  yarn.lock
Labels: automerge

#283 Make it clearer that user can manually enter name, phone, address in Send screen
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/src/recipients/RecipientPicker.tsx
  packages/mobile/src/send/SendSearchInput.tsx
  packages/mobile/src/send/__snapshots__/Send.test.tsx.snap
  packages/react-components/components/WithPasteAware.tsx
  packages/react-components/components/WithTextSearchPasteAware.tsx
Labels: automerge

#19 Upload/Download Profile Data with CIP8
  packages/mobile/Gemfile.lock
  packages/mobile/__mocks__/src/web3/contracts.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/account/Profile.tsx
  packages/mobile/src/account/UploadServiceDataWrapper.test.ts
  packages/mobile/src/account/UploadServiceDataWrapper.ts
  packages/mobile/src/account/actions.ts
  packages/mobile/src/account/profileInfo.test.ts
  packages/mobile/src/account/profileInfo.ts
  packages/mobile/src/account/reducer.ts
  packages/mobile/src/account/saga.ts
  packages/mobile/src/account/selectors.ts
  packages/mobile/src/geth/GethNativeBridgeSigner.ts
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/import/saga.test.ts
  packages/mobile/src/import/saga.ts
  packages/mobile/src/index.d.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/onboarding/registration/PictureInput.tsx
  packages/mobile/src/pincode/authentication.ts
  packages/mobile/src/send/saga.test.ts
  packages/mobile/src/send/saga.ts
  packages/mobile/src/utils/image.ts
  packages/mobile/src/web3/dataEncryptionKey.ts
  packages/mobile/src/web3/reducer.ts
  packages/mobile/test/schemas.ts
  packages/mobile/test/values.ts
  yarn.lock
Labels: automerge

#270 Add analytics events when navigating to rewards screen
  packages/mobile/e2e/src/utils/utils.js
  packages/mobile/src/account/profileInfo.ts
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.tsx
  packages/mobile/src/consumerIncentives/analyticsEventsTracker.ts
  packages/mobile/src/firebase/notifications.ts
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/import/saga.ts
  packages/mobile/src/navigator/RewardsPill.tsx
  packages/mobile/src/transactions/TransferConfirmationCard.tsx
Labels: automerge

#152 Exclude lost accounts on Secure Send
  packages/mobile/src/firebase/db-rules.json
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/identity/contactMapping.test.ts
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/identity/secureSend.ts
Labels: automerge

#286 Fix device clock sync bug
  packages/mobile/e2e/mocks/react-native-clock-sync/index.e2e.ts
  packages/mobile/e2e/mocks/react-native-clock-sync/package.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/package.json
  packages/mobile/src/account/actions.ts
  packages/mobile/src/account/reducer.ts
  packages/mobile/src/backup/DelayButton.tsx
  packages/mobile/src/backup/selectors.test.ts
  packages/mobile/src/backup/selectors.ts
  packages/mobile/src/firebase/saga.ts
  packages/mobile/src/index.d.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/set-clock/SetClock.tsx
  packages/mobile/src/utils/time.ts
  packages/mobile/src/web3/saga.ts
  yarn.lock
Labels: automerge

#295 Update 3rd party analytics so we don't need IDFA
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#294 chore: add brew update for upcoming with bintray sunset
  .circleci/config.yml
Labels: Component: Tests, automerge

#288 Show contact names on pending Escrow notification and list
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/escrow/EscrowedPaymentLineItem.test.tsx
  packages/mobile/src/escrow/EscrowedPaymentLineItem.tsx
  packages/mobile/src/escrow/EscrowedPaymentListItem.test.tsx
  packages/mobile/src/escrow/EscrowedPaymentListItem.tsx
  packages/mobile/src/escrow/EscrowedPaymentListScreen.tsx
  packages/mobile/src/escrow/EscrowedPaymentReminderSummaryNotification.test.tsx
  packages/mobile/src/escrow/EscrowedPaymentReminderSummaryNotification.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationScreen.test.tsx
  packages/mobile/src/escrow/__mocks__.ts
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentLineItem.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListScreen.test.tsx.snap
  packages/mobile/src/escrow/actions.ts
  packages/mobile/src/escrow/reducer.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/escrow/utils.ts
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/WalletHome.tsx
  packages/mobile/src/home/selectors.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/test/values.ts
Labels: automerge

#281 docs: improve templates and create template config with external links
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/2-feature-request.md
  .github/ISSUE_TEMPLATE/config.yaml
  .github/issue_template.md
  .github/pull_request_template.md
Labels: automerge, documentation, wallet
