Repository valora-inc/wallet, pull requests merged in 2021-09, with the labels that each got.

#1074 Return EOA address on WalletConnect
  packages/mobile/src/walletConnect/saga.ts
  packages/mobile/src/web3/saga.ts
Labels: automerge

#1076 Change copy of rewards screen
  packages/mobile/locales/en-US/consumerIncentives.json
  packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.tsx
  packages/mobile/src/consumerIncentives/__snapshots__/ConsumerIncentivesHomeScreen.test.tsx.snap
Labels: automerge

#1070 update readme
  packages/mobile/README.md
Labels: automerge

#1032 Fund Tests Accounts in CI Pipeline
  .github/workflows/e2e.yml
  packages/mobile/e2e/.env.enc
  packages/mobile/e2e/.gitignore
  packages/mobile/e2e/scripts/fund-e2e-accounts.ts
  packages/mobile/e2e/src/usecases/OffRamps.js
  scripts/key_placer.sh
Labels: Component: Tests, wallet, Squad: Retention

#1084 Add analytics to WalletConnect flow
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/analytics/types.ts
  packages/mobile/src/app/saga.test.ts
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/walletConnect/actions.ts
  packages/mobile/src/walletConnect/saga.ts
  packages/mobile/src/walletConnect/screens/ActionRequest.tsx
  packages/mobile/src/walletConnect/walletConnect.ts
Labels: automerge

#1079 fixing #415 requesting from phone number string
  packages/mobile/e2e/src/usecases/Support.js
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/src/recipients/RecipientPicker.tsx
  packages/mobile/src/send/Send.tsx
Labels: automerge

#1094 Separate prod from non-prod secrets
  packages/blockchain-api/src/secrets.json.enc
  packages/cloud-functions/.env.alfajores.enc
  packages/cloud-functions/.env.mainnet.enc
  packages/cloud-functions/config/rampProduction.pem.enc
  packages/cloud-functions/config/rampStaging.pem.enc
  packages/mobile/android/app/src/alfajores/google-services.json.enc
  packages/mobile/android/app/src/alfajoresdev/google-services.json.enc
  packages/mobile/android/app/src/mainnet/google-services.json.enc
  packages/mobile/android/app/src/mainnetdev/google-services.json.enc
  packages/mobile/android/sentry.properties.enc
  packages/mobile/e2e/.env.enc
  packages/mobile/ios/GoogleService-Info.alfajores.plist.enc
  packages/mobile/ios/GoogleService-Info.alfajoresdev.plist.enc
  packages/mobile/ios/GoogleService-Info.mainnet.plist.enc
  packages/mobile/ios/GoogleService-Info.mainnetdev.plist.enc
  packages/mobile/ios/sentry.properties.enc
  packages/mobile/secrets.json.enc
  packages/notification-service/config/config.alfajores.env.enc
  packages/notification-service/config/config.mainnet.env.enc
  scripts/key_placer.sh
Labels: automerge

#1095 A small fix for 'Cancel' Text button alignment in header
  packages/mobile/src/components/CancelButton.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationLoadingScreen.test.tsx.snap
Labels: automerge, wallet

#1098 Tomm/version bump 1.18.3
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/account/LicenseDisclaimer.txt
Labels: automerge

#1077 Add Cloud Function to fetch account <-> wallet address mapping
  packages/cloud-functions/.env.alfajores.enc
  packages/cloud-functions/.env.mainnet.enc
  packages/cloud-functions/README.md
  packages/cloud-functions/firebase-env-config.sh
  packages/cloud-functions/jest_setup.ts
  packages/cloud-functions/package.json
  packages/cloud-functions/src/config.ts
  packages/cloud-functions/src/database/db.ts
  packages/cloud-functions/src/index.ts
  packages/cloud-functions/src/walletAddressMapping/index.ts
  packages/cloud-functions/yarn.lock
  yarn.lock
Labels: automerge

#1101 Pin E2E Tests
  package.json
  packages/mobile/e2e/init.js
  packages/mobile/e2e/src/Pin.spec.js
  packages/mobile/e2e/src/usecases/HandleDeepLinkDappkit.js
  packages/mobile/e2e/src/usecases/NewAccountOnboarding.js
  packages/mobile/e2e/src/usecases/OffRamps.js
  packages/mobile/e2e/src/usecases/PINChange.js
  packages/mobile/e2e/src/usecases/PINRequire.js
  packages/mobile/e2e/src/utils/utils.js
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
  yarn.lock
Labels: automerge

#1086 Adding ndk stable version to the README
  packages/mobile/README.md
Labels: automerge

#1105 Add Universal Link support for WC
  packages/mobile/android/app/src/main/AndroidManifest.xml
Labels: automerge

#1108 #12 change copy on phone verification screen
  packages/mobile/locales/en-US/nuxVerification2.json
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationLoadingScreen.test.tsx.snap
Labels: automerge

#1112 Hide CICO providers that are unavailable in a user's region
  packages/cloud-functions/src/cico/fetchProviders.ts
  packages/mobile/e2e/src/usecases/OffRamps.js
  packages/mobile/e2e/src/usecases/OnRamps.js
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/ProviderOptionsScreen.test.tsx.snap
Labels: automerge

#1116 Move CICO provider filtering server-side
  packages/cloud-functions/src/cico/fetchProviders.ts
  packages/cloud-functions/src/cico/providerAvailability.ts
  packages/cloud-functions/src/cico/rampWebhook.test.ts
  packages/cloud-functions/src/cico/xanpoolWebhook.test.ts
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
Labels: automerge

#1109 Fix Google Play Services check in release builds
  packages/mobile/android/app/proguard-rules.pro
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#1134 Build Persona in app
  packages/mobile/android/build.gradle
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/ios/celo/File.swift
  packages/mobile/ios/celo/celo-Bridging-Header.h
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#1133 Fix `postinstall` script
  package.json
Labels: automerge

#1148 Fix for Flakey E2E Test
  packages/mobile/e2e/src/usecases/Support.js
Labels: automerge

#1152 Update Exchange e2e tests
  packages/mobile/e2e/src/Exchange.spec.js
  packages/mobile/e2e/src/usecases/ExchangeCelo.js
  packages/mobile/e2e/src/usecases/OffRamps.js
  packages/mobile/e2e/src/utils/utils.js
  packages/mobile/src/transactions/TransactionFeed.tsx
  packages/mobile/src/transactions/__snapshots__/TransactionFeed.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransactionsList.test.tsx.snap
Labels: automerge

#1162 fixing create account steps
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/src/account/Profile.tsx
  packages/mobile/src/import/ImportWallet.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/onboarding/registration/NameAndPicture.tsx
  packages/mobile/src/pincode/PincodeSet.tsx
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/VerificationInputScreen.tsx
Labels: automerge

#1173 1.19 Version bump
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/account/LicenseDisclaimer.txt
Labels: automerge

#1168 Make reward pill text remote configurable
  packages/mobile/src/app/reducers.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/firebase/featureFlagDefaults.e2e.ts
  packages/mobile/src/firebase/featureFlagDefaults.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/navigator/RewardsPill.tsx
  packages/mobile/src/navigator/__snapshots__/RewardsPill.test.tsx.snap
  packages/mobile/src/utils/contentTranslations.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#1174 Update invite link
  packages/mobile/.env.alfajores
  packages/mobile/.env.alfajoresdev
  packages/mobile/.env.mainnet
  packages/mobile/.env.mainnetdev
  packages/mobile/src/config.ts
  packages/mobile/src/firebase/dynamicLinks.test.ts
  packages/mobile/src/firebase/dynamicLinks.ts
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/navigator/NavigatorWrapper.tsx
Labels: automerge

#1171 Supercharge copy and UI changes
  packages/mobile/branding/celo/src/images/boost-rewards.png
  packages/mobile/locales/en-US/consumerIncentives.json
  packages/mobile/locales/es-419/consumerIncentives.json
  packages/mobile/locales/pt-BR/consumerIncentives.json
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/src/app/reducers.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.tsx
  packages/mobile/src/consumerIncentives/__snapshots__/ConsumerIncentivesHomeScreen.test.tsx.snap
  packages/mobile/src/firebase/featureFlagDefaults.e2e.ts
  packages/mobile/src/firebase/featureFlagDefaults.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/flags.ts
  packages/mobile/src/images/Images.ts
  packages/mobile/src/utils/countryFeatures.test.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#1113 WalletConnect improvements
  packages/mobile/babel.config.js
  packages/mobile/ios/celo/AppDelegate.m
  packages/mobile/locales/en-US/walletConnect.json
  packages/mobile/metro.config.js
  packages/mobile/package.json
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/app/saga.test.ts
  packages/mobile/src/exchange/__snapshots__/WithdrawCeloScreen.test.tsx.snap
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/navigator/NavigationService.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/sagas.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/src/transactions/send.ts
  packages/mobile/src/utils/useStateWithCallback.ts
  packages/mobile/src/walletConnect/constants.ts
  packages/mobile/src/walletConnect/reducer.ts
  packages/mobile/src/walletConnect/request.ts
  packages/mobile/src/walletConnect/saga.ts
  packages/mobile/src/walletConnect/screens/ActionRequest.tsx
  packages/mobile/src/walletConnect/screens/Loading.tsx
  packages/mobile/src/walletConnect/screens/Result.tsx
  packages/mobile/src/walletConnect/screens/SessionRequest.tsx
  packages/mobile/src/walletConnect/screens/Sessions.tsx
  packages/mobile/src/walletConnect/selectors.ts
  packages/mobile/src/walletConnect/types.ts
  packages/mobile/src/walletConnect/v1/actions.ts
  packages/mobile/src/walletConnect/v1/reducer.ts
  packages/mobile/src/walletConnect/v1/saga.ts
  packages/mobile/src/walletConnect/v1/selectors.ts
  packages/mobile/src/walletConnect/v2/actions.ts
  packages/mobile/src/walletConnect/v2/reducer.ts
  packages/mobile/src/walletConnect/v2/saga.ts
  packages/mobile/src/walletConnect/v2/selectors.ts
  packages/mobile/src/walletConnect/walletConnect.ts
  packages/mobile/test/schemas.ts
  packages/react-components/components/Button.tsx
  packages/walletconnect-v1/client.ts
  packages/walletconnect-v1/package.json
  packages/walletconnect-v1/types.ts
  packages/walletconnect-v2/client.ts
  packages/walletconnect-v2/package.json
  packages/walletconnect-v2/types.ts
  packages/walletconnect-v2/utils.ts
  yarn.lock
Labels: automerge

#1175 Fix Flaky Tests
  packages/mobile/e2e/src/usecases/ExchangeCelo.js
  packages/mobile/e2e/src/usecases/OnRamps.js
  packages/mobile/e2e/src/utils/utils.js
Labels: automerge

#1166 Change 'Account No.' to 'Account Address'
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/src/fiatExchanges/ExternalExchanges.tsx
  packages/mobile/src/transactions/UserSection.tsx
Labels: automerge

#1163 Add german to the app! 🇩🇪
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/ios/celo/de.lproj/InfoPlist.strings
  packages/mobile/locales/de/accountScreen10.json
  packages/mobile/locales/de/backupKeyFlow6.json
  packages/mobile/locales/de/consumerIncentives.json
  packages/mobile/locales/de/dappkit.json
  packages/mobile/locales/de/dev.json
  packages/mobile/locales/de/exchangeFlow9.json
  packages/mobile/locales/de/fiatExchangeFlow.json
  packages/mobile/locales/de/global.json
  packages/mobile/locales/de/goldEducation.json
  packages/mobile/locales/de/index.ts
  packages/mobile/locales/de/inviteFlow11.json
  packages/mobile/locales/de/nuxNamePin1.json
  packages/mobile/locales/de/nuxVerification2.json
  packages/mobile/locales/de/onboarding.json
  packages/mobile/locales/de/paymentRequestFlow.json
  packages/mobile/locales/de/receiveFlow8.json
  packages/mobile/locales/de/sendFlow7.json
  packages/mobile/locales/de/walletConnect.json
  packages/mobile/locales/de/walletFlow5.json
  packages/mobile/locales/index.ts
Labels: automerge

#1114 Support for proguard in debug builds
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/devsupport.pro
Labels: automerge

#1187 WalletConnect fixes
  packages/mobile/locales/en-US/walletConnect.json
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/walletConnect/saga.ts
  packages/mobile/src/walletConnect/screens/ActionRequest.tsx
  packages/mobile/src/walletConnect/screens/SessionRequest.tsx
Labels: automerge

#1199 Add analytics events for DappKit
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/dappkit/DappKitAccountScreen.tsx
  packages/mobile/src/dappkit/DappKitSignTxScreen.tsx
  packages/mobile/src/dappkit/dappkit.ts
Labels: automerge

#1191 Fix the CTA of the Supercharge screen
  packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.tsx
  packages/mobile/src/consumerIncentives/__snapshots__/ConsumerIncentivesHomeScreen.test.tsx.snap
Labels: automerge

#1189 Move blockchain-api from tslint to eslint
  packages/blockchain-api/.eslintrc.js
  packages/blockchain-api/package.json
  packages/blockchain-api/src/helpers/Input.ts
  packages/blockchain-api/src/index.ts
  packages/blockchain-api/test/any.test.ts
  packages/blockchain-api/tsconfig.eslint.json
  packages/blockchain-api/tslint.json
  yarn.lock
Labels: automerge

#1194 Fix WalletConnect loading screen displayed on top of the request screen sometimes
  packages/mobile/src/app/saga.test.ts
  packages/mobile/src/walletConnect/selectors.ts
  packages/mobile/src/walletConnect/walletConnect.ts
Labels: automerge

#1188 Fix WalletConnect V2
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/walletConnect/constants.ts
  packages/mobile/src/walletConnect/v1/saga.ts
  packages/mobile/src/walletConnect/v2/saga.ts
  packages/walletconnect-v2/package.json
  yarn.lock
Labels: automerge

#1201 Update Supercharge push notification
  packages/notification-service/locales/de.json
  packages/notification-service/locales/en.json
  packages/notification-service/locales/es.json
  packages/notification-service/locales/pt.json
  packages/notification-service/src/firebase.ts
  packages/notification-service/test/firebase.test.ts
Labels: automerge

#1202 Add missing @valora/eslint-config-typescript devDependencies to blockchain-api
  packages/blockchain-api/package.json
Labels: automerge

#1181 Adding editorConfig and workspace files
  packages/mobile/.editorconfig
Labels: automerge

#1205 Move notification-service from tslint to eslint
  packages/notification-service/.eslintrc.js
  packages/notification-service/package.json
  packages/notification-service/tsconfig.eslint.json
  packages/notification-service/tslint.json
Labels: automerge

#1130 Reading known addresses in blockchain-api
  packages/blockchain-api/src/helpers/EventBuilder.ts
  packages/blockchain-api/src/helpers/KnownAddressesCache.ts
  packages/blockchain-api/src/index.ts
  packages/blockchain-api/src/schema.ts
  packages/blockchain-api/test/blockscout.test.ts
  packages/blockchain-api/test/helpers/KnownAddressesCache.test.ts
  packages/mobile/src/apollo/index.ts
  packages/mobile/src/apollo/types.ts
  packages/mobile/src/firebase/notifications.ts
  packages/mobile/src/identity/saga.ts
  packages/mobile/src/recipients/recipient.ts
  packages/mobile/src/transactions/CeloTransferFeedItem.test.tsx
  packages/mobile/src/transactions/CeloTransferFeedItem.tsx
  packages/mobile/src/transactions/TransactionFeed.tsx
  packages/mobile/src/transactions/TransactionReview.test.tsx
  packages/mobile/src/transactions/TransactionReview.tsx
  packages/mobile/src/transactions/TransactionsList.test.tsx
  packages/mobile/src/transactions/TransactionsList.tsx
  packages/mobile/src/transactions/TransferConfirmationCard.tsx
  packages/mobile/src/transactions/TransferFeedItem.test.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/mobile/src/transactions/__snapshots__/CeloTransferFeedItem.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransactionsList.test.tsx.snap
  packages/mobile/src/transactions/transferFeedUtils.ts
  packages/mobile/src/transactions/utils.test.ts
Labels: automerge

#1208 Remove dev-utils
  packages/dev-utils/.gitignore
  packages/dev-utils/README.md
  packages/dev-utils/package.json
  packages/dev-utils/src/describeEach.ts
  packages/dev-utils/src/ganache-setup.ts
  packages/dev-utils/src/ganache-teardown.ts
  packages/dev-utils/src/ganache-test.ts
  packages/dev-utils/src/matchers.ts
  packages/dev-utils/src/migration-override.json
  packages/dev-utils/src/network.ts
  packages/dev-utils/tsconfig.json
  packages/dev-utils/tslint.json
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#1213 Fix screen title translation
  packages/mobile/src/account/RaiseLimitScreen.tsx
Labels: automerge

#1218 Remove tsconfig-paths devDependency
  package.json
  yarn.lock
Labels: automerge

#1217 Improve Blockchain API logging
  packages/blockchain-api/package.json
  packages/blockchain-api/src/apolloServer.ts
  packages/blockchain-api/src/blockscout.ts
  packages/blockchain-api/src/config.ts
  packages/blockchain-api/src/firebase.ts
  packages/blockchain-api/src/helpers/Input.ts
  packages/blockchain-api/src/helpers/KnownAddressesCache.ts
  packages/blockchain-api/src/index.ts
  packages/blockchain-api/src/logger.ts
  packages/blockchain-api/src/utils.ts
  yarn.lock
Labels: automerge

#1224 Tweak mobile's .eslintrc.js config to parse all the ts{x} files
  packages/mobile/.eslintrc.js
  packages/mobile/tsconfig.eslint.json
Labels: automerge

#1216 Remove last tslint vestiges
  .vscode/extensions.json
  .vscode/settings.json
  package.json
  packages/blockchain-api/src/utils.ts
  packages/cloud-functions/src/cico/providerAvailability.ts
  packages/mobile/scripts/translateFile.js
  packages/typescript/custom-rules/noGlobalArrowFunctionsRule.js
  packages/typescript/custom-rules/noGlobalArrowFunctionsRule.ts
  packages/typescript/package.json
  packages/typescript/tsconfig.json
  packages/typescript/tsconfig.library.json
  packages/typescript/tslint.json
  patches/tslint+5.20.0.patch
  yarn.lock
Labels: automerge

#1223 Reenable WalletConnect v2
  packages/mobile/src/walletConnect/saga.ts
Labels: automerge
