Repository valora-inc/wallet, pull requests merged in 2021-08, with the labels that each got.

#918 updated README for dev wallet setup
  packages/mobile/README.md
Labels: automerge

#937 Remove unused CircleCI dockerfiles
  dockerfiles/circleci/.dockerignore
  dockerfiles/circleci/Dockerfile
  dockerfiles/circleci/node10-gcloud/Dockerfile
Labels: automerge

#934 Fix reclaim invites using cEUR
  packages/mobile/locales/en-US/inviteFlow11.json
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/tokens/saga.ts
Labels: automerge

#936 Allow setting the order of in-app notifications
  packages/mobile/src/account/actions.ts
  packages/mobile/src/account/reducer.ts
  packages/mobile/src/flags.ts
  packages/mobile/src/home/NotificationBox.test.tsx
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/home/reducers.test.ts
  packages/mobile/src/home/reducers.ts
  packages/mobile/src/home/selectors.ts
  packages/react-components/components/SimpleMessagingCard.test.tsx
  packages/react-components/components/SimpleMessagingCard.tsx
Labels: automerge

#942 Update Sentry org and token
  packages/mobile/android/sentry.properties.enc
  packages/mobile/ios/sentry.properties.enc
Labels: automerge

#948 Add documentation file for deeplinks
  packages/mobile/docs/deeplinks.md
Labels: automerge

#950 Patch `tar` package
  package.json
  yarn.lock
Labels: automerge

#941 Remove deprecated cloud functions
  .gitignore
  packages/cloud-functions/src/cico/Simplex.ts
  packages/cloud-functions/src/cico/composeCicoProviderUrl.ts
  packages/cloud-functions/src/cico/processSimplexRequest.ts
  packages/cloud-functions/src/index.ts
  packages/moonpay-auth/.env.enc
  packages/moonpay-auth/.firebaserc
  packages/moonpay-auth/.gitignore
  packages/moonpay-auth/README.md
  packages/moonpay-auth/firebase.json
  packages/moonpay-auth/package.json
  packages/moonpay-auth/src/config.ts
  packages/moonpay-auth/src/index.ts
  packages/moonpay-auth/tsconfig.json
  packages/moonpay-auth/tslint.json
  packages/moonpay-auth/yarn.lock
  scripts/key_placer.sh
  yarn.lock
Labels: automerge

#947 Clean up CICO transaction labeling logic
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/actions.ts
  packages/mobile/src/fiatExchanges/reducer.ts
  packages/mobile/src/fiatExchanges/saga.test.ts
  packages/mobile/src/fiatExchanges/saga.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/firebase/saga.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#636 Implement firebase remote config
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/app/reducers.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/firebase/featureFlagDefaults.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/send/reducers.ts
  yarn.lock
Labels: automerge

#966 Fix provider icon import
  packages/mobile/src/fiatExchanges/saga.ts
  packages/mobile/src/transactions/CeloTransferFeedItem.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/mobile/src/transactions/transferFeedUtils.ts
Labels: automerge

#971 Update references to `valora-app-branding` location on GitHub
  packages/mobile/README.md
  packages/mobile/scripts/sync_branding.sh
Labels: automerge

#969 Edit CICO quote failure logging for better alerting
  packages/cloud-functions/src/bigQuery.ts
  packages/cloud-functions/src/cico/Moonpay.ts
  packages/cloud-functions/src/cico/Ramp.ts
  packages/cloud-functions/src/cico/Simplex.ts
  packages/cloud-functions/src/cico/Transak.ts
  packages/cloud-functions/src/cico/Xanpool.ts
  packages/cloud-functions/src/cico/fetchProviders.ts
  packages/cloud-functions/src/cico/fetchUserLocationData.ts
Labels: automerge

#962 Remove KomenciKit from local repo
  .gitignore
  packages/komencikit/.gitignore
  packages/komencikit/.npmignore
  packages/komencikit/AlphabeticSequencer.js
  packages/komencikit/DEVELOP.md
  packages/komencikit/README.md
  packages/komencikit/examples/attestation-flow.ts
  packages/komencikit/jest.config.js
  packages/komencikit/jest_setup.ts
  packages/komencikit/package.json
  packages/komencikit/scripts/proxy-bytecode-sha3.js
  packages/komencikit/src/actions.ts
  packages/komencikit/src/client.spec.ts
  packages/komencikit/src/client.ts
  packages/komencikit/src/errors.ts
  packages/komencikit/src/index.ts
  packages/komencikit/src/kit.spec.ts
  packages/komencikit/src/kit.ts
  packages/komencikit/src/login.ts
  packages/komencikit/src/retry.spec.ts
  packages/komencikit/src/retry.ts
  packages/komencikit/src/verifyWallet.ts
  packages/komencikit/tsconfig.json
  packages/komencikit/tslint.json
  packages/mobile/package.json
  packages/mobile/src/app/saga.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/firebase/featureFlagDefaults.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/identity/feelessVerificationErrors.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/verify/reducer.ts
  packages/mobile/src/verify/saga.test.ts
  packages/mobile/src/verify/saga.ts
  packages/mobile/src/web3/dataEncryptionKey.ts
  packages/mobile/test/schemas.ts
  packages/mobile/tsconfig.json
  yarn.lock
Labels: automerge

#968 Send analytics event when sending a push notification
  packages/indexer/config/config.mainnet.env.enc
  packages/notification-service/.gitignore
  packages/notification-service/config/config.alfajores.env
  packages/notification-service/config/config.alfajores.env.enc
  packages/notification-service/config/config.mainnet.env
  packages/notification-service/config/config.mainnet.env.enc
  packages/notification-service/package.json
  packages/notification-service/src/config.ts
  packages/notification-service/src/firebase.ts
  packages/notification-service/yarn.lock
  scripts/key_placer.sh
  yarn.lock
Labels: automerge

#973 Modify quote fetching for better error handling
  packages/cloud-functions/src/cico/Moonpay.test.ts
  packages/cloud-functions/src/cico/Moonpay.ts
  packages/cloud-functions/src/cico/Ramp.test.ts
  packages/cloud-functions/src/cico/Simplex.ts
  packages/cloud-functions/src/cico/Transak.test.ts
  packages/cloud-functions/src/cico/Transak.ts
  packages/cloud-functions/src/cico/Xanpool.test.ts
  packages/cloud-functions/src/cico/Xanpool.ts
  packages/cloud-functions/src/config.ts
Labels: automerge

#978 Migration notice in packages/indexer/README.md
  packages/indexer/README.md
Labels: automerge

#905 Remove obsolete code
  .dockerignore
  .env
  .env.alfajores
  .env.baklava
  .env.mnemonic.alfajores.enc
  .env.mnemonic.baklava.enc
  .env.mnemonic.enc
  .env.mnemonic.rc1.enc
  .env.oracledev
  .env.rc1
  .gitbook.yaml
  cloudbuild.yaml
Labels: tech-debt

#981 Build Plaid on both Android and iOS
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/androidTest/AndroidManifest.xml
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainApplication.java
  packages/mobile/android/build.gradle
  packages/mobile/android/settings.gradle
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#985 Use isLoading to disable withdrawal button
  packages/mobile/src/exchange/WithdrawCeloReviewScreen.tsx
Labels: automerge, wallet

#987 Label invite rewards correctly in the feed
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/src/config.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/recipients/reducer.ts
  packages/mobile/src/recipients/saga.ts
  packages/mobile/src/transactions/TransactionReview.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/mobile/src/transactions/transferFeedUtils.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#988 Some cEUR invite fixes
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/src/escrow/EscrowedPaymentListItem.test.tsx
  packages/mobile/src/escrow/EscrowedPaymentListItem.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationScreen.tsx
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListItem.test.tsx.snap
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/tokens/saga.ts
Labels: automerge

#1005 Merge Release/wallet/1.17.0
  packages/mobile/Gemfile.lock
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/account/LicenseDisclaimer.txt
Labels: automerge

#1014 Add push notifications for invite rewards
  packages/notification-service/locales/en.json
  packages/notification-service/src/firebase.ts
  packages/notification-service/src/index.ts
  packages/notification-service/src/invites/invites.ts
  packages/notification-service/src/polling.ts
  packages/notification-service/test/firebase.test.ts
  packages/notification-service/test/invites.test.ts
Labels: automerge

#956 Adding CEUR balance to the Bidali screen
  packages/mobile/src/fiatExchanges/BidaliScreen.test.tsx
  packages/mobile/src/fiatExchanges/BidaliScreen.tsx
  packages/mobile/src/fiatExchanges/saga.test.ts
Labels: automerge

#955 Delete flake-tracker package
  .github/CODEOWNERS
  dependency-graph.json
  packages/blockchain-api/jest.config.js
  packages/blockchain-api/package.json
  packages/cloud-functions/jest.config.js
  packages/flake-tracker/README.md
  packages/flake-tracker/package.json
  packages/flake-tracker/scripts/summary.js
  packages/flake-tracker/src/config.js
  packages/flake-tracker/src/db.js
  packages/flake-tracker/src/github.js
  packages/flake-tracker/src/jest/config.js
  packages/flake-tracker/src/jest/environments/detox.js
  packages/flake-tracker/src/jest/environments/jsdom.js
  packages/flake-tracker/src/jest/environments/node.js
  packages/flake-tracker/src/jest/setup.global.js
  packages/flake-tracker/src/jest/setup.js
  packages/flake-tracker/src/jest/teardown.global.js
  packages/flake-tracker/src/jest/tracker.js
  packages/flake-tracker/src/jest/utils.js
  packages/flake-tracker/src/manager.js
  packages/flake-tracker/src/mocha/config.js
  packages/flake-tracker/src/mocha/reporter.js
  packages/flake-tracker/src/mocha/utils.js
  packages/flake-tracker/src/utils.js
  packages/mobile/jest.config.js
  packages/mobile/package.json
  packages/mobile/scripts/run_e2e.sh
  packages/notification-service/jest.config.js
  packages/notification-service/package.json
  packages/react-components/jest.config.js
  packages/react-components/package.json
  yarn.lock
Labels: tech-debt

#1021 Batch Mobile Tests
  packages/mobile/package.json
  packages/mobile/src/backup/__snapshots__/BackupPhraseContainer.test.tsx.snap
  packages/mobile/src/components/__snapshots__/Avatar.test.tsx.snap
  packages/mobile/src/fiatExchanges/BidaliScreen.test.tsx
  packages/mobile/src/fiatExchanges/saga.test.ts
  packages/mobile/test/merge-coverage.ts
  packages/mobile/test/run-tests-ci.ts
  yarn.lock
Labels: automerge, Component: Tests, wallet

#1008 test: run e2e tests nightly on main
  .github/workflows/e2e.yml
Labels: automerge

#1029 Enable cEUR with Bidali
  packages/mobile/e2e/src/usecases/OffRamps.js
  packages/mobile/src/app/saga.test.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/fiatExchanges/BidaliScreen.test.tsx
  packages/mobile/src/fiatExchanges/BidaliScreen.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/fiatExchanges/saga.test.ts
  packages/mobile/src/fiatExchanges/saga.ts
  packages/mobile/src/firebase/featureFlagDefaults.e2e.ts
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/stableToken/selectors.ts
  packages/mobile/src/tokens/utils.test.ts
  packages/mobile/src/tokens/utils.ts
  packages/mobile/src/utils/currencies.ts
Labels: automerge

#1045 Hide invite item in side menu
  packages/mobile/src/flags.ts
  packages/mobile/src/navigator/DrawerNavigator.tsx
Labels: automerge
